#!/bin/bash
# Quick reference for LLM audit findings

echo "═══════════════════════════════════════════════════════════════"
echo "  LLM TRACKING AUDIT - QUICK REFERENCE"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "📊 TRACKING COVERAGE"
echo "─────────────────────────────────────────────────────────────"
echo "✅ TRACKED:     2 files (22%)"
echo "  • rag-orchestrator.ts (action: 'extract')"
echo "  • siret-extractor.ts (partial - no options)"
echo ""
echo "❌ UNTRACKED:   7 files (78%)"
echo "  • generate-embedding/index.ts       - OpenAI embeddings"
echo "  • llm-completion/index.ts (x2)      - OpenAI + Anthropic"
echo "  • analyze-photo/index.ts            - GPT-4 Vision"
echo "  • ingest-document/index.ts          - Document OCR"
echo "  • scripts/rag-reingest.ts           - SDK embeddings"
echo "  • src/services/ai/claude.service.ts - Client-side Anthropic"
echo ""

echo "💰 COST IMPACT"
echo "─────────────────────────────────────────────────────────────"
echo "Untracked daily:     ~80 API calls"
echo "Untracked monthly:   ~2,400 requests"
echo "Untracked tokens:    ~30-40M tokens/month"
echo "Untracked costs:     ~$300-450/month ❌"
echo ""

echo "🔧 REQUIRED CHANGES"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "1. ADD TO ai-client.ts:"
echo "   ├─ generateEmbedding()   (for OpenAI embeddings)"
echo "   ├─ analyzeImage()        (for GPT-4 Vision)"
echo "   └─ callOpenAI()          (for general completions)"
echo ""
echo "2. REFACTOR EDGE FUNCTIONS:"
echo "   ├─ generate-embedding/index.ts      (1h)"
echo "   ├─ llm-completion/index.ts          (2h)"
echo "   ├─ analyze-photo/index.ts           (1h)"
echo "   ├─ ingest-document/index.ts         (1.5h)"
echo "   └─ scripts/rag-reingest.ts          (1h)"
echo ""
echo "3. TOTAL EFFORT: ~9 hours"
echo ""

echo "📋 UNTRACKED FUNCTIONS DETAIL"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "FILE: generate-embedding/index.ts"
echo "LINE: 36"
echo "CALL: fetch('https://api.openai.com/v1/embeddings')"
echo "TRACKING: ❌ NONE"
echo ""

echo "FILE: llm-completion/index.ts"
echo "LINE: 132 (Anthropic)"
echo "CALL: fetch('https://api.anthropic.com/v1/messages')"
echo "TRACKING: ❌ NONE"
echo ""
echo "LINE: 160 (OpenAI)"
echo "CALL: fetch('https://api.openai.com/v1/chat/completions')"
echo "TRACKING: ❌ NONE"
echo ""

echo "FILE: analyze-photo/index.ts"
echo "LINE: 309"
echo "CALL: fetch('https://api.openai.com/v1/chat/completions') [Vision]"
echo "TRACKING: ❌ NONE"
echo "COST: HIGH (expensive Vision API)"
echo ""

echo "FILE: ingest-document/index.ts"
echo "LINE: 75"
echo "CALL: fetch('https://api.openai.com/v1/chat/completions') [OCR]"
echo "TRACKING: ❌ NONE"
echo ""

echo "FILE: scripts/rag-reingest.ts"
echo "LINE: 21 (import), 41 (init)"
echo "SDK: import OpenAI from 'openai'"
echo "TRACKING: ❌ NONE"
echo ""

echo "FILE: src/services/ai/claude.service.ts"
echo "LINE: 13 (import), 42 (init)"
echo "SDK: import Anthropic from '@anthropic-ai/sdk'"
echo "TRACKING: ❌ NONE (client-side, can't track easily)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  DETAILED REPORTS:"
echo "  • LLM_AUDIT_REPORT.md      (comprehensive audit)"
echo "  • LLM_USAGE_TRACKING.md    (tracking implementation)"
echo "═══════════════════════════════════════════════════════════════"
