/**
 * Page de consultation d'un AO (B2B Entreprise)
 * Affiche les détails, DCE et permet de lancer une réponse
 */

import React, { useEffect, useState, useCallback } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Separator } from '@/components/ui/separator';
import { Progress } from '@/components/ui/progress';
import {
  ArrowLeft, FileText, Download, Eye, Clock, Send, Calendar,
  Briefcase, AlertTriangle, Loader2, MapPin, Euro, Building,
  CheckCircle2, Phone, Mail, FileSpreadsheet, TrendingUp,
  Target, Lightbulb, AlertCircle
} from 'lucide-react';
import { TenderService } from '@/services/tender/tender.service';
import { ResponseService } from '@/services/tender/response.service';
import { supabase } from '@/lib/supabase';
import type { Tender, TenderDocument, TenderResponse } from '@/types/tender';
import { useApp } from '@/context/AppContext';
import { useToast } from '@/hooks/use-toast';

export function B2BTenderViewPage() {
  const { tenderId } = useParams<{ tenderId: string }>();
  const navigate = useNavigate();
  const { user } = useApp();
  const { toast } = useToast();

  const [tender, setTender] = useState<Tender | null>(null);
  const [documents, setDocuments] = useState<TenderDocument[]>([]);
  const [existingResponse, setExistingResponse] = useState<TenderResponse | null>(null);
  const [dceAnalysis, setDceAnalysis] = useState<{ keyInfo: string[]; requirements: string[] } | null>(null);
  const [positioningScore, setPositioningScore] = useState<number | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [isStartingResponse, setIsStartingResponse] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Charger les données
  useEffect(() => {
    const loadTender = async () => {
      if (!tenderId) return;

      setIsLoading(true);
      setError(null);

      try {
        const tenderData = await TenderService.getById(tenderId);
        if (!tenderData) {
          setError('Appel d\'offres non trouvé');
          return;
        }

        setTender(tenderData);

        // Charger les documents
        const { data: docsData } = await supabase
          .from('tender_documents')
          .select('*')
          .eq('tender_id', tenderId)
          .eq('is_public', true)
          .order('document_type');

        if (docsData) {
          setDocuments(docsData.map(d => ({
            id: d.id,
            tenderId: d.tender_id,
            documentType: d.document_type,
            name: d.name,
            description: d.description,
            version: d.version,
            generatedContent: d.generated_content,
            isAutoGenerated: d.is_auto_generated,
            isRequired: d.is_required,
            isPublic: d.is_public,
            createdAt: new Date(d.created_at),
            updatedAt: new Date(d.updated_at),
          })));
        }

        // Vérifier si une réponse existe déjà
        if (user?.id) {
          try {
            const responses = await ResponseService.listByCompany(user.id);
            const existing = responses.find(r => r.tenderId === tenderId);
            if (existing) {
              setExistingResponse(existing);
            }
          } catch (respErr) {
            console.log('Pas de réponse existante');
          }
        }

        // Enregistrer la vue
        await TenderService.recordView(tenderId);

      } catch (err) {
        console.error('Erreur chargement AO:', err);
        setError('Impossible de charger l\'appel d\'offres');
      } finally {
        setIsLoading(false);
      }
    };

    loadTender();
  }, [tenderId, user?.id]);

  // Analyser le DCE
  const analyzeDCE = useCallback(async () => {
    if (!tender || !documents.length) return;

    setIsAnalyzing(true);
    try {
      const analysis = await ResponseService.analyzeDCE(tender, documents);
      setDceAnalysis({
        keyInfo: analysis.keyInfo || [],
        requirements: analysis.requirements || [],
      });
      toast({
        title: 'Analyse terminée',
        description: 'Les informations clés du DCE ont été extraites',
      });
    } catch (err) {
      console.error('Erreur analyse DCE:', err);
      toast({
        title: 'Erreur',
        description: 'Impossible d\'analyser le DCE',
        variant: 'destructive',
      });
    } finally {
      setIsAnalyzing(false);
    }
  }, [tender, documents, toast]);

  // Calculer le score de positionnement
  const calculatePositioning = useCallback(async () => {
    if (!tender || !user?.id) return;

    try {
      const score = await ResponseService.calculatePositioningScore(tender, user.id);
      setPositioningScore(score);
    } catch (err) {
      console.error('Erreur calcul positionnement:', err);
    }
  }, [tender, user?.id]);

  // Démarrer une réponse
  const startResponse = useCallback(async () => {
    if (!tender || !user) return;

    setIsStartingResponse(true);
    try {
      const response = await ResponseService.createDraft({
        tenderId: tender.id,
        companySiret: user.siret || 'SIRET_A_RENSEIGNER',
        companyName: user.companyName || user.email || 'Entreprise',
      });

      toast({
        title: 'Brouillon créé',
        description: 'Vous pouvez maintenant préparer votre réponse',
      });

      navigate(`/b2b/ao/${tender.id}/response/${response.id}`);
    } catch (err) {
      console.error('Erreur création réponse:', err);
      toast({
        title: 'Erreur',
        description: 'Impossible de créer la réponse',
        variant: 'destructive',
      });
    } finally {
      setIsStartingResponse(false);
    }
  }, [tender, user, toast, navigate]);

  // Télécharger le DCE
  const downloadDCE = useCallback(() => {
    // TODO: Générer un ZIP avec tous les documents DCE
    toast({
      title: 'Téléchargement',
      description: 'Le téléchargement du DCE va commencer...',
    });
  }, [toast]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error || !tender) {
    return (
      <div className="container max-w-4xl mx-auto px-4 py-8">
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription>{error || 'Appel d\'offres non trouvé'}</AlertDescription>
        </Alert>
        <Button variant="outline" className="mt-4" onClick={() => navigate('/b2b/ao')}>
          <ArrowLeft className="w-4 h-4 mr-2" />
          Retour aux AO
        </Button>
      </div>
    );
  }

  const isExpired = tender.responseDeadline && new Date(tender.responseDeadline) < new Date();
  const daysLeft = tender.responseDeadline
    ? Math.ceil((new Date(tender.responseDeadline).getTime() - Date.now()) / (1000 * 60 * 60 * 24))
    : null;

  return (
    <div className="min-h-screen bg-muted/20">
      <div className="container max-w-6xl mx-auto px-4 py-8">
        {/* Navigation */}
        <div className="flex items-center justify-between mb-6">
          <Button variant="ghost" asChild>
            <Link to="/b2b/ao">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Appels d'offres
            </Link>
          </Button>
          <div className="flex items-center gap-2">
            <Button variant="outline" onClick={downloadDCE}>
              <Download className="w-4 h-4 mr-2" />
              Télécharger DCE
            </Button>
            {!isExpired && !existingResponse && (
              <Button onClick={startResponse} disabled={isStartingResponse}>
                {isStartingResponse ? (
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                ) : (
                  <Send className="w-4 h-4 mr-2" />
                )}
                Répondre à cet AO
              </Button>
            )}
            {existingResponse && (
              <Button onClick={() => navigate(`/b2b/ao/${tender.id}/response/${existingResponse.id}`)}>
                <Eye className="w-4 h-4 mr-2" />
                {existingResponse.status === 'draft' ? 'Continuer ma réponse' : 'Voir ma réponse'}
              </Button>
            )}
          </div>
        </div>

        {/* En-tête */}
        <Card className="mb-6">
          <CardHeader>
            <div className="flex items-start justify-between">
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <Badge variant="outline" className="font-mono">
                    {tender.reference}
                  </Badge>
                  {isExpired ? (
                    <Badge variant="destructive">Consultation terminée</Badge>
                  ) : daysLeft !== null && daysLeft <= 7 ? (
                    <Badge variant="outline" className="text-orange-500 border-orange-500">
                      <Clock className="w-3 h-3 mr-1" />
                      J-{daysLeft} restants
                    </Badge>
                  ) : (
                    <Badge variant="default">En cours</Badge>
                  )}
                  {existingResponse && (
                    <Badge variant="secondary">
                      {existingResponse.status === 'draft' && 'Réponse en cours'}
                      {existingResponse.status === 'submitted' && 'Réponse envoyée'}
                      {existingResponse.status === 'selected' && 'Marché gagné !'}
                    </Badge>
                  )}
                </div>
                <CardTitle className="text-2xl">{tender.title}</CardTitle>
                {tender.description && (
                  <CardDescription className="mt-2">
                    {tender.description}
                  </CardDescription>
                )}
              </div>
              <div className="text-right">
                {tender.responseDeadline && (
                  <>
                    <div className="text-sm text-muted-foreground">Date limite</div>
                    <div className="text-lg font-bold text-primary">
                      {tender.responseDeadline.toLocaleDateString('fr-FR')}
                    </div>
                  </>
                )}
              </div>
            </div>
          </CardHeader>
        </Card>

        {/* Alerte si expiré */}
        {isExpired && (
          <Alert variant="destructive" className="mb-6">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              La date limite de réponse est dépassée. Vous ne pouvez plus soumettre de réponse à cet appel d'offres.
            </AlertDescription>
          </Alert>
        )}

        {/* Score de positionnement */}
        {positioningScore !== null && (
          <Card className="mb-6 border-primary/30">
            <CardHeader className="pb-2">
              <CardTitle className="text-lg flex items-center gap-2">
                <Target className="w-5 h-5 text-primary" />
                Score de positionnement
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-4">
                <Progress value={positioningScore} className="flex-1" />
                <div className="text-2xl font-bold text-primary">{positioningScore}%</div>
              </div>
              <p className="text-sm text-muted-foreground mt-2">
                {positioningScore >= 70
                  ? 'Excellent match ! Ce marché correspond à votre profil.'
                  : positioningScore >= 50
                  ? 'Bon potentiel, mais veillez à bien valoriser vos points forts.'
                  : 'Ce marché présente des challenges, assurez-vous de répondre aux exigences.'}
              </p>
            </CardContent>
          </Card>
        )}

        {/* Contenu */}
        <Tabs defaultValue="overview">
          <TabsList className="mb-6">
            <TabsTrigger value="overview">Vue d'ensemble</TabsTrigger>
            <TabsTrigger value="dce">Documents DCE ({documents.length})</TabsTrigger>
            <TabsTrigger value="analysis">
              <Lightbulb className="w-4 h-4 mr-2" />
              Analyse IA
            </TabsTrigger>
          </TabsList>

          {/* Vue d'ensemble */}
          <TabsContent value="overview" className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Informations projet */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <Briefcase className="w-5 h-5 text-primary" />
                    Informations projet
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3 text-sm">
                  {tender.workAddress && (
                    <div className="flex items-start gap-2">
                      <MapPin className="w-4 h-4 text-muted-foreground mt-0.5" />
                      <div>
                        <div>{tender.workAddress.street}</div>
                        <div className="text-muted-foreground">
                          {tender.workPostalCode} {tender.workCity}
                        </div>
                      </div>
                    </div>
                  )}
                  {(tender.estimatedBudgetMin || tender.estimatedBudgetMax) && tender.budgetVisibility !== 'hidden' && (
                    <div className="flex items-center gap-2">
                      <Euro className="w-4 h-4 text-muted-foreground" />
                      <span>
                        Budget indicatif: {tender.estimatedBudgetMin?.toLocaleString('fr-FR')} € - {tender.estimatedBudgetMax?.toLocaleString('fr-FR')} €
                      </span>
                    </div>
                  )}
                  {tender.estimatedDurationDays && (
                    <div className="flex items-center gap-2">
                      <Clock className="w-4 h-4 text-muted-foreground" />
                      <span>Durée estimée: {Math.ceil(tender.estimatedDurationDays / 7)} semaines</span>
                    </div>
                  )}
                  {tender.desiredStartDate && (
                    <div className="flex items-center gap-2">
                      <Calendar className="w-4 h-4 text-muted-foreground" />
                      <span>Démarrage souhaité: {tender.desiredStartDate.toLocaleDateString('fr-FR')}</span>
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Contact MOA */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <Building className="w-5 h-5 text-primary" />
                    Contact Maître d'Ouvrage
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3 text-sm">
                  {tender.contactName && (
                    <div className="font-medium">{tender.contactName}</div>
                  )}
                  {tender.contactEmail && (
                    <div className="flex items-center gap-2">
                      <Mail className="w-4 h-4 text-muted-foreground" />
                      <a href={`mailto:${tender.contactEmail}`} className="text-primary hover:underline">
                        {tender.contactEmail}
                      </a>
                    </div>
                  )}
                  {tender.contactPhone && (
                    <div className="flex items-center gap-2">
                      <Phone className="w-4 h-4 text-muted-foreground" />
                      <a href={`tel:${tender.contactPhone}`} className="text-primary hover:underline">
                        {tender.contactPhone}
                      </a>
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Dates clés */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <Calendar className="w-5 h-5 text-primary" />
                    Dates clés
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3 text-sm">
                  {tender.publishedAt && (
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Publication</span>
                      <span>{tender.publishedAt.toLocaleDateString('fr-FR')}</span>
                    </div>
                  )}
                  {tender.questionsDeadline && (
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Limite questions</span>
                      <span>{tender.questionsDeadline.toLocaleDateString('fr-FR')}</span>
                    </div>
                  )}
                  {tender.responseDeadline && (
                    <div className="flex justify-between font-medium">
                      <span>Limite réponses</span>
                      <span className={isExpired ? 'text-destructive' : 'text-primary'}>
                        {tender.responseDeadline.toLocaleDateString('fr-FR')}
                      </span>
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Critères d'évaluation */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <CheckCircle2 className="w-5 h-5 text-primary" />
                    Critères de jugement
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {tender.evaluationCriteria.map((criterion, i) => (
                      <div key={i}>
                        <div className="flex justify-between mb-1">
                          <span className="text-sm capitalize">{criterion.name}</span>
                          <span className="text-sm font-medium">{criterion.weight}%</span>
                        </div>
                        <Progress value={criterion.weight} className="h-2" />
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Lots */}
            {tender.selectedLots && tender.selectedLots.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg">Lots de travaux</CardTitle>
                  <CardDescription>
                    {tender.lotsCount} lot(s) - Vous pouvez répondre à un ou plusieurs lots
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {tender.selectedLots.map((lot) => (
                      <div
                        key={lot.lotNumber}
                        className="flex items-center justify-between p-4 border rounded-lg"
                      >
                        <div className="flex items-center gap-3">
                          <Badge variant="outline" className="font-mono">
                            Lot {lot.lotNumber}
                          </Badge>
                          <div>
                            <div className="font-medium">{lot.lotName}</div>
                            {lot.description && (
                              <div className="text-sm text-muted-foreground mt-1">
                                {lot.description}
                              </div>
                            )}
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          {lot.rgeRequired && (
                            <Badge variant="secondary">RGE requis</Badge>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Exigences */}
            {tender.requirements && (
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg">Exigences</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2">
                    {tender.requirements.rgeRequired && (
                      <Badge>Certification RGE obligatoire</Badge>
                    )}
                    {tender.requirements.insuranceDecennaleRequired && (
                      <Badge variant="outline">Assurance décennale</Badge>
                    )}
                    {tender.requirements.insuranceRcProRequired && (
                      <Badge variant="outline">RC Professionnelle</Badge>
                    )}
                    {tender.requirements.requiredQualifications?.map((q, i) => (
                      <Badge key={i} variant="secondary">{q}</Badge>
                    ))}
                    {tender.requirements.minYearsExperience && (
                      <Badge variant="outline">
                        {tender.requirements.minYearsExperience}+ ans d'expérience
                      </Badge>
                    )}
                  </div>
                </CardContent>
              </Card>
            )}
          </TabsContent>

          {/* Documents DCE */}
          <TabsContent value="dce" className="space-y-6">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="flex items-center gap-2">
                      <FileSpreadsheet className="w-5 h-5" />
                      Dossier de Consultation des Entreprises
                    </CardTitle>
                    <CardDescription>
                      Téléchargez les documents pour préparer votre réponse
                    </CardDescription>
                  </div>
                  <Button onClick={downloadDCE}>
                    <Download className="w-4 h-4 mr-2" />
                    Télécharger tout
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                {documents.length > 0 ? (
                  <div className="space-y-3">
                    {documents.map((doc) => (
                      <div
                        key={doc.id}
                        className="flex items-center justify-between p-4 border rounded-lg hover:bg-muted/50"
                      >
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                            <FileText className="w-5 h-5 text-primary" />
                          </div>
                          <div>
                            <div className="font-medium">{doc.name}</div>
                            <div className="text-sm text-muted-foreground">
                              {doc.documentType.toUpperCase()}
                              {doc.description && ` • ${doc.description}`}
                            </div>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          {doc.isRequired && (
                            <Badge variant="outline" className="text-xs">Obligatoire</Badge>
                          )}
                          <Button variant="ghost" size="icon">
                            <Eye className="w-4 h-4" />
                          </Button>
                          <Button variant="ghost" size="icon">
                            <Download className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-8 text-muted-foreground">
                    <FileText className="w-12 h-12 mx-auto mb-2 opacity-50" />
                    <p>Aucun document disponible</p>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          {/* Analyse IA */}
          <TabsContent value="analysis" className="space-y-6">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="flex items-center gap-2">
                      <Lightbulb className="w-5 h-5 text-yellow-500" />
                      Analyse intelligente
                    </CardTitle>
                    <CardDescription>
                      Laissez l'IA vous aider à préparer votre réponse
                    </CardDescription>
                  </div>
                  {!dceAnalysis && (
                    <Button onClick={analyzeDCE} disabled={isAnalyzing}>
                      {isAnalyzing ? (
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      ) : (
                        <TrendingUp className="w-4 h-4 mr-2" />
                      )}
                      Analyser le DCE
                    </Button>
                  )}
                </div>
              </CardHeader>
              <CardContent>
                {dceAnalysis ? (
                  <div className="space-y-6">
                    {/* Informations clés */}
                    <div>
                      <h4 className="font-medium mb-3 flex items-center gap-2">
                        <CheckCircle2 className="w-4 h-4 text-green-500" />
                        Informations clés extraites
                      </h4>
                      <ul className="space-y-2">
                        {dceAnalysis.keyInfo.map((info, i) => (
                          <li key={i} className="flex items-start gap-2 text-sm">
                            <span className="text-green-500 mt-1">•</span>
                            <span>{info}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    <Separator />

                    {/* Exigences à vérifier */}
                    <div>
                      <h4 className="font-medium mb-3 flex items-center gap-2">
                        <AlertTriangle className="w-4 h-4 text-yellow-500" />
                        Points d'attention
                      </h4>
                      <ul className="space-y-2">
                        {dceAnalysis.requirements.map((req, i) => (
                          <li key={i} className="flex items-start gap-2 text-sm">
                            <span className="text-yellow-500 mt-1">!</span>
                            <span>{req}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    <Separator />

                    {/* Score de positionnement */}
                    {positioningScore === null && (
                      <div className="text-center py-4">
                        <Button variant="outline" onClick={calculatePositioning}>
                          <Target className="w-4 h-4 mr-2" />
                          Calculer mon score de positionnement
                        </Button>
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="text-center py-12 text-muted-foreground">
                    <Lightbulb className="w-12 h-12 mx-auto mb-4 opacity-50" />
                    <h3 className="text-lg font-semibold mb-2">Analyse IA disponible</h3>
                    <p className="max-w-md mx-auto mb-4">
                      Notre IA peut analyser le DCE pour extraire les informations clés,
                      identifier les exigences et évaluer votre positionnement.
                    </p>
                    <Button onClick={analyzeDCE} disabled={isAnalyzing}>
                      {isAnalyzing ? (
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      ) : (
                        <TrendingUp className="w-4 h-4 mr-2" />
                      )}
                      Lancer l'analyse
                    </Button>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}

export default B2BTenderViewPage;
