/**
 * TORP DCE Generator Service
 * Génération automatique du Dossier de Consultation des Entreprises
 *
 * Documents générés :
 * - RC (Règlement de Consultation)
 * - CCTP (via le service existant)
 * - DPGF (Décomposition du Prix Global Forfaitaire)
 * - Planning prévisionnel
 * - AE (Acte d'Engagement) - template
 */

import { supabase } from '@/lib/supabase';
import type { Phase0Project } from '@/types/phase0/project.types';
import type {
  Tender,
  TenderDocument,
  TenderLot,
  DCEDocumentType,
  DocumentContent,
  DocumentSection,
} from '@/types/tender';
import { DocumentGeneratorService } from '@/services/phase0/documentGenerator.service';
import { EstimationService } from '@/services/phase0/estimation.service';
import { KnowledgeService } from '@/services/rag/knowledge.service';

// =============================================================================
// TYPES INTERNES
// =============================================================================

interface DCEGenerationResult {
  tender: Tender;
  documents: TenderDocument[];
  errors: string[];
}

interface DPGFLot {
  lotNumber: string;
  lotName: string;
  lotType: string;
  items: DPGFItem[];
  totalHT: number;
}

interface DPGFItem {
  reference: string;
  designation: string;
  unit: string;
  quantity: number;
  unitPriceHT: number;
  totalHT: number;
}

interface PlanningPhase {
  name: string;
  lots: string[];
  startWeek: number;
  endWeek: number;
  durationWeeks: number;
  dependencies?: string[];
}

// =============================================================================
// DCE GENERATOR SERVICE
// =============================================================================

export class DCEGeneratorService {
  /**
   * Génère l'ensemble du DCE pour un appel d'offres
   */
  static async generateDCE(
    tender: Tender,
    phase0Project: Phase0Project
  ): Promise<DCEGenerationResult> {
    const documents: TenderDocument[] = [];
    const errors: string[] = [];

    console.log('[DCEGenerator] Starting DCE generation for tender:', tender.reference);

    try {
      // 1. Générer le RC (Règlement de Consultation)
      const rcDoc = await this.generateRC(tender, phase0Project);
      documents.push(rcDoc);
      console.log('[DCEGenerator] RC generated');
    } catch (error) {
      console.error('[DCEGenerator] RC generation error:', error);
      errors.push(`Erreur génération RC: ${error}`);
    }

    try {
      // 2. Générer le CCTP (réutilise le service existant)
      const cctpContent = await DocumentGeneratorService.generateCCTPEnriched(phase0Project);
      const cctpDoc = await this.saveTenderDocument(tender.id, {
        documentType: 'cctp',
        name: `CCTP - ${tender.title}`,
        description: 'Cahier des Clauses Techniques Particulières',
        generatedContent: cctpContent,
        isAutoGenerated: true,
        isRequired: true,
      });
      documents.push(cctpDoc);
      console.log('[DCEGenerator] CCTP generated');
    } catch (error) {
      console.error('[DCEGenerator] CCTP generation error:', error);
      errors.push(`Erreur génération CCTP: ${error}`);
    }

    try {
      // 3. Générer le DPGF
      const dpgfDoc = await this.generateDPGF(tender, phase0Project);
      documents.push(dpgfDoc);
      console.log('[DCEGenerator] DPGF generated');
    } catch (error) {
      console.error('[DCEGenerator] DPGF generation error:', error);
      errors.push(`Erreur génération DPGF: ${error}`);
    }

    try {
      // 4. Générer le Planning
      const planningDoc = await this.generatePlanning(tender, phase0Project);
      documents.push(planningDoc);
      console.log('[DCEGenerator] Planning generated');
    } catch (error) {
      console.error('[DCEGenerator] Planning generation error:', error);
      errors.push(`Erreur génération Planning: ${error}`);
    }

    try {
      // 5. Générer l'Acte d'Engagement (template)
      const aeDoc = await this.generateAE(tender, phase0Project);
      documents.push(aeDoc);
      console.log('[DCEGenerator] AE generated');
    } catch (error) {
      console.error('[DCEGenerator] AE generation error:', error);
      errors.push(`Erreur génération AE: ${error}`);
    }

    // Mettre à jour le tender avec les documents générés
    const updatedTender = await this.updateTenderWithDCE(tender.id, documents);

    return {
      tender: updatedTender,
      documents,
      errors,
    };
  }

  // ===========================================================================
  // RC - RÈGLEMENT DE CONSULTATION
  // ===========================================================================

  /**
   * Génère le Règlement de Consultation
   */
  static async generateRC(
    tender: Tender,
    phase0Project: Phase0Project
  ): Promise<TenderDocument> {
    const sections: DocumentSection[] = [];

    // 1. Objet de la consultation
    sections.push({
      id: 'objet',
      title: '1. OBJET DE LA CONSULTATION',
      level: 1,
      content: this.generateRCObjet(tender, phase0Project),
    });

    // 2. Conditions de la consultation
    sections.push({
      id: 'conditions',
      title: '2. CONDITIONS DE LA CONSULTATION',
      level: 1,
      content: this.generateRCConditions(tender),
      subsections: [
        {
          id: 'conditions-procedure',
          title: '2.1 Procédure de passation',
          level: 2,
          content: this.getRCProcedure(tender),
        },
        {
          id: 'conditions-lots',
          title: '2.2 Décomposition en lots',
          level: 2,
          content: this.getRCLots(tender),
        },
        {
          id: 'conditions-variantes',
          title: '2.3 Variantes',
          level: 2,
          content: 'Les variantes ne sont pas autorisées sauf mention contraire dans le présent document.',
        },
        {
          id: 'conditions-delai',
          title: '2.4 Délai de validité des offres',
          level: 2,
          content: 'Le délai de validité des offres est fixé à 90 jours à compter de la date limite de réception des offres.',
        },
      ],
    });

    // 3. Contenu du dossier de consultation
    sections.push({
      id: 'dossier',
      title: '3. CONTENU DU DOSSIER DE CONSULTATION',
      level: 1,
      content: this.generateRCDossier(),
    });

    // 4. Présentation des candidatures et des offres
    sections.push({
      id: 'presentation',
      title: '4. PRÉSENTATION DES CANDIDATURES ET DES OFFRES',
      level: 1,
      content: this.generateRCPresentation(tender),
    });

    // 5. Critères de jugement
    sections.push({
      id: 'criteres',
      title: '5. CRITÈRES DE JUGEMENT DES OFFRES',
      level: 1,
      content: this.generateRCCriteres(tender),
    });

    // 6. Conditions d'envoi
    sections.push({
      id: 'envoi',
      title: '6. CONDITIONS D\'ENVOI DES OFFRES',
      level: 1,
      content: this.generateRCEnvoi(tender),
    });

    // 7. Renseignements complémentaires
    sections.push({
      id: 'renseignements',
      title: '7. RENSEIGNEMENTS COMPLÉMENTAIRES',
      level: 1,
      content: this.generateRCRenseignements(tender),
    });

    const content: DocumentContent = { sections };

    return this.saveTenderDocument(tender.id, {
      documentType: 'rc',
      name: `RC - ${tender.title}`,
      description: 'Règlement de Consultation',
      generatedContent: content,
      isAutoGenerated: true,
      isRequired: true,
    });
  }

  private static generateRCObjet(tender: Tender, project: Phase0Project): string {
    const lines: string[] = [];

    lines.push('1.1 OBJET DU MARCHÉ');
    lines.push('');
    lines.push(`Le présent marché a pour objet : ${tender.title}`);
    lines.push('');

    if (tender.description) {
      lines.push(tender.description);
      lines.push('');
    }

    lines.push('1.2 LIEU D\'EXÉCUTION');
    lines.push('');
    if (tender.workAddress) {
      lines.push(`${tender.workAddress.street || ''}`);
      lines.push(`${tender.workPostalCode} ${tender.workCity}`);
    }
    lines.push('');

    lines.push('1.3 MAÎTRE D\'OUVRAGE');
    lines.push('');
    lines.push(`${tender.contactName || 'Non précisé'}`);
    if (tender.contactEmail) lines.push(`Email: ${tender.contactEmail}`);
    if (tender.contactPhone) lines.push(`Téléphone: ${tender.contactPhone}`);

    return lines.join('\n');
  }

  private static generateRCConditions(tender: Tender): string {
    return 'Le présent document fixe les conditions de la consultation.';
  }

  private static getRCProcedure(tender: Tender): string {
    const procedures: Record<string, string> = {
      simple: 'Consultation simple - Marché privé de travaux',
      mapa: 'Marché à Procédure Adaptée (MAPA) en application de l\'article L2123-1 du Code de la commande publique',
      appel_offres: 'Appel d\'offres ouvert en application des articles L2124-2 et R2124-2 du Code de la commande publique',
      restreint: 'Appel d\'offres restreint en application des articles L2124-3 et R2124-3 du Code de la commande publique',
    };

    return procedures[tender.tenderType] || procedures.simple;
  }

  private static getRCLots(tender: Tender): string {
    if (!tender.selectedLots?.length) {
      return 'Le marché fait l\'objet d\'un lot unique.';
    }

    const lines: string[] = [];
    lines.push(`Le marché est décomposé en ${tender.lotsCount} lot(s) :`);
    lines.push('');

    tender.selectedLots.forEach(lot => {
      lines.push(`- Lot ${lot.lotNumber} : ${lot.lotName}`);
      if (lot.description) {
        lines.push(`  ${lot.description}`);
      }
    });

    lines.push('');
    lines.push('Les candidats peuvent présenter une offre pour un ou plusieurs lots.');
    lines.push('Les lots pourront être attribués à un ou plusieurs titulaires.');

    return lines.join('\n');
  }

  private static generateRCDossier(): string {
    return `Le dossier de consultation des entreprises (DCE) comprend les pièces suivantes :

PIÈCES GÉNÉRALES :
- Le présent Règlement de Consultation (RC)
- L'Acte d'Engagement (AE) à compléter par le candidat

PIÈCES TECHNIQUES :
- Le Cahier des Clauses Techniques Particulières (CCTP)
- Le Décomposition du Prix Global et Forfaitaire (DPGF)
- Le Planning prévisionnel
- Les plans et documents graphiques (si fournis)

PIÈCES ADMINISTRATIVES (à fournir par le candidat) :
- Attestation d'assurance Responsabilité Civile Professionnelle
- Attestation d'assurance Décennale
- Extrait Kbis de moins de 3 mois
- Attestations fiscales et sociales
- Références de chantiers similaires`;
  }

  private static generateRCPresentation(tender: Tender): string {
    const lines: string[] = [];

    lines.push('4.1 DOCUMENTS À PRODUIRE');
    lines.push('');
    lines.push('L\'offre du candidat comprendra :');
    lines.push('');
    lines.push('A - PIÈCES DE LA CANDIDATURE :');
    lines.push('  • Lettre de candidature (ou formulaire DC1 pour les marchés publics)');
    lines.push('  • Déclaration du candidat (ou formulaire DC2 pour les marchés publics)');
    lines.push('  • Attestations d\'assurances en cours de validité');
    lines.push('  • Extrait Kbis ou équivalent de moins de 3 mois');

    if (tender.requirements?.rgeRequired) {
      lines.push('  • Certificat RGE en cours de validité pour les lots concernés');
    }

    if (tender.requirements?.requiredQualifications?.length) {
      lines.push(`  • Justificatifs de qualifications : ${tender.requirements.requiredQualifications.join(', ')}`);
    }

    lines.push('');
    lines.push('B - PIÈCES DE L\'OFFRE :');
    lines.push('  • L\'Acte d\'Engagement (AE) dûment complété et signé');
    lines.push('  • Le DPGF complété avec les prix unitaires et totaux');
    lines.push('  • Un mémoire technique présentant :');
    lines.push('    - Les moyens humains et matériels affectés au chantier');
    lines.push('    - La méthodologie d\'exécution');
    lines.push('    - Le planning détaillé d\'exécution');
    lines.push('    - Les mesures de sécurité et de protection de l\'environnement');
    lines.push('  • Les références de chantiers similaires (3 minimum)');

    return lines.join('\n');
  }

  private static generateRCCriteres(tender: Tender): string {
    const lines: string[] = [];

    lines.push('Les offres seront jugées selon les critères suivants :');
    lines.push('');

    tender.evaluationCriteria.forEach(criterion => {
      lines.push(`• ${criterion.name.charAt(0).toUpperCase() + criterion.name.slice(1)} : ${criterion.weight}%`);
      if (criterion.description) {
        lines.push(`  ${criterion.description}`);
      }
    });

    lines.push('');
    lines.push('Le maître d\'ouvrage se réserve le droit de négocier avec les candidats ayant présenté les offres les plus intéressantes.');

    return lines.join('\n');
  }

  private static generateRCEnvoi(tender: Tender): string {
    const lines: string[] = [];

    lines.push('6.1 DATE LIMITE DE RÉCEPTION DES OFFRES');
    lines.push('');
    if (tender.responseDeadline) {
      const deadline = new Date(tender.responseDeadline);
      lines.push(`Les offres devront parvenir avant le ${deadline.toLocaleDateString('fr-FR')} à ${deadline.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' })}.`);
    } else {
      lines.push('La date limite de réception des offres sera précisée ultérieurement.');
    }

    lines.push('');
    lines.push('6.2 MODALITÉS D\'ENVOI');
    lines.push('');
    lines.push('Les offres peuvent être transmises :');
    lines.push('  • Par voie électronique via la plateforme TORP');
    lines.push('  • Par courrier recommandé avec accusé de réception à l\'adresse du maître d\'ouvrage');
    lines.push('');
    lines.push('Toute offre reçue après la date et l\'heure limites sera déclarée irrecevable.');

    return lines.join('\n');
  }

  private static generateRCRenseignements(tender: Tender): string {
    const lines: string[] = [];

    lines.push('7.1 DEMANDE DE RENSEIGNEMENTS');
    lines.push('');
    lines.push('Les candidats peuvent poser leurs questions via la plateforme TORP ou par email.');

    if (tender.questionsDeadline) {
      const deadline = new Date(tender.questionsDeadline);
      lines.push(`Les questions devront être posées au plus tard le ${deadline.toLocaleDateString('fr-FR')}.`);
    }

    lines.push('');
    lines.push('Les réponses aux questions seront transmises à l\'ensemble des candidats.');
    lines.push('');
    lines.push('7.2 VISITE DU SITE');
    lines.push('');
    lines.push('Une visite du site est fortement recommandée. Les candidats sont invités à prendre rendez-vous avec le maître d\'ouvrage.');
    lines.push('');
    lines.push('7.3 CONTACT');
    lines.push('');
    if (tender.contactName) lines.push(`Contact : ${tender.contactName}`);
    if (tender.contactEmail) lines.push(`Email : ${tender.contactEmail}`);
    if (tender.contactPhone) lines.push(`Téléphone : ${tender.contactPhone}`);

    return lines.join('\n');
  }

  // ===========================================================================
  // DPGF - DÉCOMPOSITION DU PRIX GLOBAL FORFAITAIRE
  // ===========================================================================

  /**
   * Génère le DPGF
   */
  static async generateDPGF(
    tender: Tender,
    phase0Project: Phase0Project
  ): Promise<TenderDocument> {
    const sections: DocumentSection[] = [];

    // En-tête
    sections.push({
      id: 'header',
      title: 'DÉCOMPOSITION DU PRIX GLOBAL ET FORFAITAIRE',
      level: 1,
      content: this.generateDPGFHeader(tender),
    });

    // Instructions
    sections.push({
      id: 'instructions',
      title: 'INSTRUCTIONS',
      level: 1,
      content: this.generateDPGFInstructions(),
    });

    // Générer le DPGF pour chaque lot
    const dpgfLots = await this.generateDPGFLots(tender, phase0Project);

    dpgfLots.forEach((lot, index) => {
      sections.push({
        id: `lot-${lot.lotType}`,
        title: `LOT ${lot.lotNumber} - ${lot.lotName.toUpperCase()}`,
        level: 1,
        content: this.formatDPGFLot(lot),
      });
    });

    // Récapitulatif
    sections.push({
      id: 'recap',
      title: 'RÉCAPITULATIF GÉNÉRAL',
      level: 1,
      content: this.generateDPGFRecap(dpgfLots, tender),
    });

    const content: DocumentContent = {
      sections,
      metadata: {
        dpgfLots,
      },
    };

    return this.saveTenderDocument(tender.id, {
      documentType: 'dpgf',
      name: `DPGF - ${tender.title}`,
      description: 'Décomposition du Prix Global et Forfaitaire',
      generatedContent: content,
      isAutoGenerated: true,
      isRequired: true,
    });
  }

  private static generateDPGFHeader(tender: Tender): string {
    return `Affaire : ${tender.title}
Référence : ${tender.reference}
Adresse : ${tender.workAddress?.street || ''}, ${tender.workPostalCode} ${tender.workCity}

Ce document doit être complété par le candidat avec ses prix.
Les quantités sont données à titre indicatif et devront être vérifiées par l'entreprise.`;
  }

  private static generateDPGFInstructions(): string {
    return `MODALITÉS DE REMPLISSAGE :

1. Compléter la colonne "Prix Unitaire HT" pour chaque ligne
2. Calculer le montant total HT de chaque ligne (Quantité × Prix Unitaire)
3. Reporter les totaux par lot dans le récapitulatif
4. Calculer le montant total HT de l'offre
5. Appliquer le taux de TVA approprié (10% ou 20% selon la nature des travaux)
6. Dater et signer le document

UNITÉS :
- U : Unité
- m² : Mètre carré
- ml : Mètre linéaire
- m³ : Mètre cube
- Ens : Ensemble
- Fft : Forfait
- h : Heure`;
  }

  private static async generateDPGFLots(
    tender: Tender,
    project: Phase0Project
  ): Promise<DPGFLot[]> {
    const dpgfLots: DPGFLot[] = [];

    for (const lot of (tender.selectedLots || [])) {
      const items = this.generateDPGFItemsForLot(lot, project);

      dpgfLots.push({
        lotNumber: lot.lotNumber,
        lotName: lot.lotName,
        lotType: lot.lotType,
        items,
        totalHT: 0, // À remplir par l'entreprise
      });
    }

    return dpgfLots;
  }

  private static generateDPGFItemsForLot(
    lot: TenderLot,
    project: Phase0Project
  ): DPGFItem[] {
    const items: DPGFItem[] = [];
    const surface = project.property?.characteristics?.livingArea || 100;

    // Générer des items selon le type de lot
    const lotItems = this.getDefaultItemsForLotType(lot.lotType, surface);

    // Ajouter les prestations spécifiques si définies
    if (lot.prestations?.length) {
      lot.prestations.forEach((prestation, index) => {
        items.push({
          reference: `${lot.lotNumber}.${(index + 1).toString().padStart(2, '0')}`,
          designation: prestation,
          unit: 'Ens',
          quantity: 1,
          unitPriceHT: 0,
          totalHT: 0,
        });
      });
    } else {
      items.push(...lotItems);
    }

    return items;
  }

  private static getDefaultItemsForLotType(lotType: string, surface: number): DPGFItem[] {
    // Items par défaut selon le type de lot
    const defaultItems: Record<string, DPGFItem[]> = {
      demolition: [
        { reference: '01.01', designation: 'Installation de chantier, protections', unit: 'Fft', quantity: 1, unitPriceHT: 0, totalHT: 0 },
        { reference: '01.02', designation: 'Démolition cloisons légères', unit: 'm²', quantity: Math.round(surface * 0.3), unitPriceHT: 0, totalHT: 0 },
        { reference: '01.03', designation: 'Démolition revêtements de sol', unit: 'm²', quantity: surface, unitPriceHT: 0, totalHT: 0 },
        { reference: '01.04', designation: 'Évacuation des gravats', unit: 'm³', quantity: Math.round(surface * 0.1), unitPriceHT: 0, totalHT: 0 },
        { reference: '01.05', designation: 'Nettoyage fin de chantier', unit: 'Fft', quantity: 1, unitPriceHT: 0, totalHT: 0 },
      ],
      platrerie: [
        { reference: '16.01', designation: 'Cloisons BA13 sur ossature métallique', unit: 'm²', quantity: Math.round(surface * 0.4), unitPriceHT: 0, totalHT: 0 },
        { reference: '16.02', designation: 'Doublage isolant sur ossature', unit: 'm²', quantity: Math.round(surface * 0.5), unitPriceHT: 0, totalHT: 0 },
        { reference: '16.03', designation: 'Faux plafond BA13', unit: 'm²', quantity: surface, unitPriceHT: 0, totalHT: 0 },
        { reference: '16.04', designation: 'Bandes et enduits', unit: 'Fft', quantity: 1, unitPriceHT: 0, totalHT: 0 },
      ],
      courants_forts: [
        { reference: '27.01', designation: 'Tableau électrique complet', unit: 'U', quantity: 1, unitPriceHT: 0, totalHT: 0 },
        { reference: '27.02', designation: 'Prises de courant 16A', unit: 'U', quantity: Math.round(surface / 8), unitPriceHT: 0, totalHT: 0 },
        { reference: '27.03', designation: 'Points lumineux (interrupteur + câblage)', unit: 'U', quantity: Math.round(surface / 10), unitPriceHT: 0, totalHT: 0 },
        { reference: '27.04', designation: 'Mise à la terre', unit: 'Fft', quantity: 1, unitPriceHT: 0, totalHT: 0 },
        { reference: '27.05', designation: 'Consuel', unit: 'Fft', quantity: 1, unitPriceHT: 0, totalHT: 0 },
      ],
      sanitaires: [
        { reference: '31.01', designation: 'WC suspendu complet', unit: 'U', quantity: 1, unitPriceHT: 0, totalHT: 0 },
        { reference: '31.02', designation: 'Lavabo avec robinetterie', unit: 'U', quantity: 1, unitPriceHT: 0, totalHT: 0 },
        { reference: '31.03', designation: 'Douche à l\'italienne complète', unit: 'U', quantity: 1, unitPriceHT: 0, totalHT: 0 },
        { reference: '31.04', designation: 'Raccordements EU/EV', unit: 'Fft', quantity: 1, unitPriceHT: 0, totalHT: 0 },
      ],
      carrelage: [
        { reference: '22.01', designation: 'Carrelage sol (fourniture et pose)', unit: 'm²', quantity: surface, unitPriceHT: 0, totalHT: 0 },
        { reference: '22.02', designation: 'Faïence murale', unit: 'm²', quantity: Math.round(surface * 0.2), unitPriceHT: 0, totalHT: 0 },
        { reference: '22.03', designation: 'Plinthes', unit: 'ml', quantity: Math.round(surface * 0.4), unitPriceHT: 0, totalHT: 0 },
        { reference: '22.04', designation: 'Joints et finitions', unit: 'Fft', quantity: 1, unitPriceHT: 0, totalHT: 0 },
      ],
      peinture: [
        { reference: '24.01', designation: 'Préparation des supports (rebouchage, ponçage)', unit: 'm²', quantity: surface * 2.5, unitPriceHT: 0, totalHT: 0 },
        { reference: '24.02', designation: 'Impression et 2 couches peinture murs', unit: 'm²', quantity: surface * 2.5, unitPriceHT: 0, totalHT: 0 },
        { reference: '24.03', designation: 'Peinture plafonds', unit: 'm²', quantity: surface, unitPriceHT: 0, totalHT: 0 },
        { reference: '24.04', designation: 'Peinture boiseries et menuiseries', unit: 'ml', quantity: Math.round(surface * 0.3), unitPriceHT: 0, totalHT: 0 },
      ],
      menuiseries_interieures: [
        { reference: '19.01', designation: 'Bloc-porte intérieur standard', unit: 'U', quantity: Math.round(surface / 15), unitPriceHT: 0, totalHT: 0 },
        { reference: '19.02', designation: 'Plinthes bois', unit: 'ml', quantity: Math.round(surface * 0.4), unitPriceHT: 0, totalHT: 0 },
      ],
    };

    return defaultItems[lotType] || [
      { reference: '00.01', designation: 'Travaux selon descriptif CCTP', unit: 'Ens', quantity: 1, unitPriceHT: 0, totalHT: 0 },
    ];
  }

  private static formatDPGFLot(lot: DPGFLot): string {
    const lines: string[] = [];

    lines.push('┌─────────┬────────────────────────────────────────────┬────────┬──────────┬──────────────┬──────────────┐');
    lines.push('│ Réf.    │ Désignation                                │ Unité  │ Quantité │ P.U. HT (€)  │ Total HT (€) │');
    lines.push('├─────────┼────────────────────────────────────────────┼────────┼──────────┼──────────────┼──────────────┤');

    lot.items.forEach(item => {
      const ref = item.reference.padEnd(7);
      const designation = item.designation.substring(0, 42).padEnd(42);
      const unit = item.unit.padEnd(6);
      const qty = item.quantity.toString().padStart(8);
      const pu = '_____________';
      const total = '_____________';
      lines.push(`│ ${ref} │ ${designation} │ ${unit} │ ${qty} │ ${pu} │ ${total} │`);
    });

    lines.push('├─────────┴────────────────────────────────────────────┴────────┴──────────┼──────────────┼──────────────┤');
    lines.push('│                                                     TOTAL LOT HT (€) :  │              │ ___________ │');
    lines.push('└─────────────────────────────────────────────────────────────────────────┴──────────────┴──────────────┘');

    return lines.join('\n');
  }

  private static generateDPGFRecap(lots: DPGFLot[], tender: Tender): string {
    const lines: string[] = [];

    lines.push('┌──────────────────────────────────────────────────────────────────────┬──────────────┐');
    lines.push('│ LOT                                                                  │ MONTANT HT   │');
    lines.push('├──────────────────────────────────────────────────────────────────────┼──────────────┤');

    lots.forEach(lot => {
      const lotLine = `Lot ${lot.lotNumber} - ${lot.lotName}`.substring(0, 68).padEnd(68);
      lines.push(`│ ${lotLine} │ ___________ │`);
    });

    lines.push('├──────────────────────────────────────────────────────────────────────┼──────────────┤');
    lines.push('│ TOTAL HT                                                             │ ___________ │');
    lines.push('├──────────────────────────────────────────────────────────────────────┼──────────────┤');
    lines.push('│ TVA (taux applicable : ___%)                                         │ ___________ │');
    lines.push('├──────────────────────────────────────────────────────────────────────┼──────────────┤');
    lines.push('│ TOTAL TTC                                                            │ ___________ │');
    lines.push('└──────────────────────────────────────────────────────────────────────┴──────────────┘');

    lines.push('');
    lines.push('Fait à ________________, le ___/___/______');
    lines.push('');
    lines.push('Cachet et signature de l\'entreprise :');

    return lines.join('\n');
  }

  // ===========================================================================
  // PLANNING
  // ===========================================================================

  /**
   * Génère le planning prévisionnel
   */
  static async generatePlanning(
    tender: Tender,
    project: Phase0Project
  ): Promise<TenderDocument> {
    const estimation = EstimationService.estimateProject(project);
    const phases = this.generatePlanningPhases(tender, estimation);

    const sections: DocumentSection[] = [];

    // En-tête
    sections.push({
      id: 'header',
      title: 'PLANNING PRÉVISIONNEL D\'EXÉCUTION',
      level: 1,
      content: this.generatePlanningHeader(tender, estimation),
    });

    // Phases
    sections.push({
      id: 'phases',
      title: 'PHASAGE DES TRAVAUX',
      level: 1,
      content: this.formatPlanningPhases(phases),
    });

    // Diagramme de Gantt simplifié
    sections.push({
      id: 'gantt',
      title: 'DIAGRAMME PRÉVISIONNEL',
      level: 1,
      content: this.generateGanttDiagram(phases, estimation),
    });

    // Contraintes
    sections.push({
      id: 'contraintes',
      title: 'CONTRAINTES DE PLANNING',
      level: 1,
      content: this.generatePlanningConstraints(project),
    });

    const content: DocumentContent = {
      sections,
      metadata: { phases, estimation },
    };

    return this.saveTenderDocument(tender.id, {
      documentType: 'planning',
      name: `Planning - ${tender.title}`,
      description: 'Planning prévisionnel d\'exécution',
      generatedContent: content,
      isAutoGenerated: true,
      isRequired: true,
    });
  }

  private static generatePlanningPhases(
    tender: Tender,
    estimation: ReturnType<typeof EstimationService.estimateProject>
  ): PlanningPhase[] {
    const phases: PlanningPhase[] = [];
    let currentWeek = 1;

    // Phase 0 : Installation chantier
    phases.push({
      name: 'Installation de chantier',
      lots: ['Préparation'],
      startWeek: currentWeek,
      endWeek: currentWeek,
      durationWeeks: 1,
    });
    currentWeek += 1;

    // Regrouper les lots par phase d'exécution
    const lotGroups: Record<string, string[]> = {
      'Démolition / Préparation': ['demolition', 'terrassement_vrd'],
      'Gros œuvre': ['maconnerie', 'beton_arme', 'charpente_bois', 'charpente_metallique', 'ossature_bois'],
      'Couverture / Étanchéité': ['couverture', 'etancheite'],
      'Menuiseries extérieures': ['menuiseries_exterieures', 'fermetures'],
      'Cloisonnement / Isolation': ['isolation_interieure', 'platrerie', 'cloisons_humides', 'faux_plafonds'],
      'Électricité': ['courants_forts', 'courants_faibles', 'domotique'],
      'Plomberie / Sanitaires': ['sanitaires', 'eau_chaude', 'assainissement'],
      'Chauffage / Ventilation': ['chauffage_central', 'chauffage_bois', 'climatisation', 'plancher_chauffant', 'radiateurs', 'vmc_simple_flux', 'vmc_double_flux'],
      'Finitions sol': ['sols_souples', 'carrelage', 'parquet'],
      'Finitions murs / Peinture': ['peinture', 'menuiseries_interieures'],
      'Aménagements extérieurs': ['amenagements_exterieurs', 'clotures', 'eclairage_exterieur'],
    };

    const tenderLotTypes = new Set((tender.selectedLots || []).map(l => l.lotType));

    Object.entries(lotGroups).forEach(([phaseName, lotTypes]) => {
      const matchingLots = lotTypes.filter(lt => tenderLotTypes.has(lt));
      if (matchingLots.length > 0) {
        const duration = Math.max(1, Math.ceil(matchingLots.length * 1.5));
        phases.push({
          name: phaseName,
          lots: matchingLots,
          startWeek: currentWeek,
          endWeek: currentWeek + duration - 1,
          durationWeeks: duration,
        });
        currentWeek += duration;
      }
    });

    // Phase finale : Réception
    phases.push({
      name: 'Nettoyage et réception',
      lots: ['Finitions'],
      startWeek: currentWeek,
      endWeek: currentWeek,
      durationWeeks: 1,
    });

    return phases;
  }

  private static generatePlanningHeader(
    tender: Tender,
    estimation: ReturnType<typeof EstimationService.estimateProject>
  ): string {
    const lines: string[] = [];

    lines.push(`Affaire : ${tender.title}`);
    lines.push(`Référence : ${tender.reference}`);
    lines.push('');
    lines.push(`Durée prévisionnelle : ${estimation.duration.totalWeeks.min} à ${estimation.duration.totalWeeks.max} semaines`);

    if (tender.desiredStartDate) {
      lines.push(`Date de démarrage souhaitée : ${new Date(tender.desiredStartDate).toLocaleDateString('fr-FR')}`);
    }

    lines.push('');
    lines.push('Ce planning est donné à titre indicatif. L\'entreprise proposera son propre planning détaillé dans son offre.');

    return lines.join('\n');
  }

  private static formatPlanningPhases(phases: PlanningPhase[]): string {
    const lines: string[] = [];

    phases.forEach((phase, index) => {
      lines.push(`${index + 1}. ${phase.name}`);
      lines.push(`   Semaines ${phase.startWeek} à ${phase.endWeek} (${phase.durationWeeks} semaine(s))`);
      if (phase.lots.length > 0 && phase.lots[0] !== 'Préparation' && phase.lots[0] !== 'Finitions') {
        lines.push(`   Lots concernés : ${phase.lots.join(', ')}`);
      }
      lines.push('');
    });

    return lines.join('\n');
  }

  private static generateGanttDiagram(
    phases: PlanningPhase[],
    estimation: ReturnType<typeof EstimationService.estimateProject>
  ): string {
    const totalWeeks = Math.max(...phases.map(p => p.endWeek), estimation.duration.totalWeeks.max);
    const lines: string[] = [];

    // En-tête avec numéros de semaine
    let header = 'Phase'.padEnd(30) + '│';
    for (let w = 1; w <= Math.min(totalWeeks, 20); w++) {
      header += w.toString().padStart(2) + '│';
    }
    if (totalWeeks > 20) header += '...│';

    lines.push(header);
    lines.push('─'.repeat(30) + '┼' + '──┼'.repeat(Math.min(totalWeeks, 20)) + (totalWeeks > 20 ? '───┤' : ''));

    // Lignes pour chaque phase
    phases.forEach(phase => {
      let line = phase.name.substring(0, 29).padEnd(30) + '│';
      for (let w = 1; w <= Math.min(totalWeeks, 20); w++) {
        if (w >= phase.startWeek && w <= phase.endWeek) {
          line += '██│';
        } else {
          line += '  │';
        }
      }
      if (totalWeeks > 20) {
        if (phase.endWeek > 20) {
          line += '███│';
        } else {
          line += '   │';
        }
      }
      lines.push(line);
    });

    return lines.join('\n');
  }

  private static generatePlanningConstraints(project: Phase0Project): string {
    const lines: string[] = [];
    const constraints = project.workProject?.constraints;

    lines.push('L\'entreprise devra tenir compte des contraintes suivantes :');
    lines.push('');

    // Contraintes temporelles
    if (constraints?.temporal) {
      if (constraints.temporal.blackoutPeriods?.length) {
        lines.push('• Périodes d\'exclusion :');
        constraints.temporal.blackoutPeriods.forEach(period => {
          lines.push(`  - ${period.reason || 'Période non travaillée'}`);
        });
      }
      if (constraints.temporal.isUrgent) {
        lines.push('• Travaux à caractère urgent');
      }
    }

    // Contraintes d'occupation
    if (constraints?.occupancy?.duringWorks) {
      const occupancyLabels: Record<string, string> = {
        vacant: '• Logement vacant pendant les travaux',
        occupied_full: '• Logement occupé - travaux par phases obligatoires',
        occupied_partial: '• Logement partiellement occupé - coordination nécessaire',
      };
      if (occupancyLabels[constraints.occupancy.duringWorks]) {
        lines.push(occupancyLabels[constraints.occupancy.duringWorks]);
      }
    }

    // Contraintes de copropriété
    if (project.property?.condo?.isInCondo) {
      lines.push('• Contraintes de copropriété : respect des horaires et règlement');
    }

    if (lines.length === 2) {
      lines.push('• Aucune contrainte particulière identifiée');
    }

    return lines.join('\n');
  }

  // ===========================================================================
  // ACTE D'ENGAGEMENT
  // ===========================================================================

  /**
   * Génère l'Acte d'Engagement (template)
   */
  static async generateAE(
    tender: Tender,
    project: Phase0Project
  ): Promise<TenderDocument> {
    const sections: DocumentSection[] = [];

    sections.push({
      id: 'header',
      title: 'ACTE D\'ENGAGEMENT',
      level: 1,
      content: `
Affaire : ${tender.title}
Référence : ${tender.reference}

Ce document doit être complété, daté et signé par le représentant habilité de l'entreprise.`,
    });

    sections.push({
      id: 'identification-moa',
      title: 'A. IDENTIFICATION DU MAÎTRE D\'OUVRAGE',
      level: 1,
      content: this.generateAEMOA(tender, project),
    });

    sections.push({
      id: 'identification-entreprise',
      title: 'B. IDENTIFICATION DE L\'ENTREPRISE',
      level: 1,
      content: this.generateAEEntreprise(),
    });

    sections.push({
      id: 'objet',
      title: 'C. OBJET DU MARCHÉ',
      level: 1,
      content: `
${tender.title}

Lieu d'exécution : ${tender.workAddress?.street || ''}, ${tender.workPostalCode} ${tender.workCity}

Lots concernés :
${(tender.selectedLots || []).map(l => `  • Lot ${l.lotNumber} - ${l.lotName}`).join('\n')}`,
    });

    sections.push({
      id: 'engagement',
      title: 'D. ENGAGEMENT DU CANDIDAT',
      level: 1,
      content: this.generateAEEngagement(tender),
    });

    sections.push({
      id: 'signature',
      title: 'E. SIGNATURE',
      level: 1,
      content: this.generateAESignature(),
    });

    const content: DocumentContent = { sections };

    return this.saveTenderDocument(tender.id, {
      documentType: 'ae',
      name: `AE - ${tender.title}`,
      description: 'Acte d\'Engagement',
      generatedContent: content,
      isAutoGenerated: true,
      isRequired: true,
    });
  }

  private static generateAEMOA(tender: Tender, project: Phase0Project): string {
    return `
Nom / Raison sociale : ${tender.contactName || '__________________________'}
Adresse : ${tender.workAddress?.street || '__________________________'}
          ${tender.workPostalCode || '_____'} ${tender.workCity || '__________________________'}
Téléphone : ${tender.contactPhone || '__________________________'}
Email : ${tender.contactEmail || '__________________________'}`;
  }

  private static generateAEEntreprise(): string {
    return `
Raison sociale : ______________________________________________
Forme juridique : ______________________________________________
Capital social : ______________________________________________ €
N° SIRET : ______________________________________________
Code APE/NAF : ______________________________________________
N° TVA intracommunautaire : ______________________________________________

Adresse du siège social :
______________________________________________
______________________________________________

Représentant légal :
Nom et prénom : ______________________________________________
Qualité : ______________________________________________
Téléphone : ______________________________________________
Email : ______________________________________________

Personne à contacter pour ce marché (si différent) :
Nom et prénom : ______________________________________________
Téléphone : ______________________________________________
Email : ______________________________________________`;
  }

  private static generateAEEngagement(tender: Tender): string {
    return `
Après avoir pris connaissance du dossier de consultation et notamment :
- Du Règlement de Consultation (RC)
- Du Cahier des Clauses Techniques Particulières (CCTP)
- Du Décomposition du Prix Global et Forfaitaire (DPGF)
- Du Planning prévisionnel

Je soussigné(e), représentant l'entreprise désignée ci-dessus, m'engage :

1. À exécuter les prestations objet du présent marché aux conditions suivantes :

   Montant total HT : _________________________ €
   (en lettres : _______________________________________________)

   TVA (___%) : _________________________ €

   Montant total TTC : _________________________ €
   (en lettres : _______________________________________________)

2. À réaliser les travaux dans un délai de _________ jours / semaines
   à compter de l'ordre de service de démarrage.

3. À maintenir cette offre valable pendant un délai de 90 jours
   à compter de la date limite de remise des offres.

4. À fournir une attestation d'assurance décennale et RC Pro
   avant le démarrage des travaux.

☐ Je dispose des qualifications RGE requises pour ce marché
☐ Je ne dispose pas des qualifications RGE (cocher si applicable)`;
  }

  private static generateAESignature(): string {
    return `
Fait à _________________________, le _____/_____/_________

En _____ exemplaire(s) original(aux)

Le représentant de l'entreprise,
(cachet, nom, qualité et signature)




______________________________________________`;
  }

  // ===========================================================================
  // HELPERS
  // ===========================================================================

  /**
   * Sauvegarde un document DCE
   */
  private static async saveTenderDocument(
    tenderId: string,
    doc: {
      documentType: DCEDocumentType;
      name: string;
      description?: string;
      generatedContent?: DocumentContent;
      isAutoGenerated?: boolean;
      isRequired?: boolean;
    }
  ): Promise<TenderDocument> {
    const { data, error } = await supabase
      .from('tender_documents')
      .insert({
        tender_id: tenderId,
        document_type: doc.documentType,
        name: doc.name,
        description: doc.description,
        generated_content: doc.generatedContent,
        is_auto_generated: doc.isAutoGenerated ?? false,
        is_required: doc.isRequired ?? true,
        is_public: true,
        version: 1,
      })
      .select()
      .single();

    if (error) {
      console.error('[DCEGenerator] Save document error:', error);
      throw error;
    }

    return {
      id: data.id,
      tenderId: data.tender_id,
      documentType: data.document_type,
      name: data.name,
      description: data.description,
      version: data.version,
      generatedContent: data.generated_content,
      isAutoGenerated: data.is_auto_generated,
      isRequired: data.is_required,
      isPublic: data.is_public,
      createdAt: new Date(data.created_at),
      updatedAt: new Date(data.updated_at),
    };
  }

  /**
   * Met à jour le tender avec les documents générés
   */
  private static async updateTenderWithDCE(
    tenderId: string,
    documents: TenderDocument[]
  ): Promise<Tender> {
    const { data, error } = await supabase
      .from('tenders')
      .update({
        dce_documents: documents.map(d => ({
          id: d.id,
          type: d.documentType,
          name: d.name,
        })),
        dce_generated_at: new Date().toISOString(),
        status: 'ready',
        updated_at: new Date().toISOString(),
      })
      .eq('id', tenderId)
      .select()
      .single();

    if (error) {
      console.error('[DCEGenerator] Update tender error:', error);
      throw error;
    }

    // Re-mapper (import du service pour éviter la dépendance circulaire)
    return {
      ...data,
      createdAt: new Date(data.created_at),
      updatedAt: new Date(data.updated_at),
    } as unknown as Tender;
  }
}

export default DCEGeneratorService;
