/**
 * Knowledge Index Service v2.0 (Phase 30, upgraded Phase 42)
 * Indexes chunks into pgvector and provides SQL-level semantic search.
 *
 * Key changes from v1.0:
 *  - Bug fix: getSupabaseClient() did not exist — replaced with supabase import
 *  - Embeddings written to `embedding_vector` (vector(1536)) via targeted UPDATE per chunk (Phase 42 upgrade)
 *  - semanticSearch() uses supabase.rpc('match_knowledge_chunks') — no in-memory scan
 *  - Backward-compat: existing rows with the old `embedding` column are not touched
 */
import { generateEmbedding } from './knowledgeEmbedding.service';
import { verifyAndPersistIntegrity } from '../integrity/knowledgeIntegrity.service';
import { getKnowledgeConflictService } from '../conflicts/knowledgeConflict.service';
import { supabase } from '@/lib/supabase';
import { log, warn, error } from '@/lib/logger';

// ---------------------------------------------------------------------------
// Query Embedding Cache
// ---------------------------------------------------------------------------

// Cache query embeddings to avoid repeated OpenAI calls for identical queries during runtime.
const queryEmbeddingCache = new Map<string, number[]>();

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface IndexStats {
  chunksIndexed: number;
  embeddingsGenerated: number;
  indexSize: number;
  lastUpdated: string;
}

// ---------------------------------------------------------------------------
// indexChunks
// ---------------------------------------------------------------------------

/**
 * PHASE 41: PASSIVE MODE - Index chunks for knowledge base (verification only)
 *
 * This function does NOT generate embeddings. All embeddings must be generated
 * by the ingestion pipeline (knowledgeStepRunner) before calling this function.
 *
 * Responsibilities:
 * 1. Verify embeddings exist in database
 * 2. Run integrity verification (blocking, feeds is_publishable flag)
 * 3. Run conflict detection (non-blocking)
 *
 * @param documentId - Document ID
 * @param chunks - Chunks to verify (embeddings should already exist in database)
 * @returns Success status
 */
export async function indexChunks(documentId: string, chunks: ChunkerChunk[]): Promise<boolean> {
  if (!documentId) {
    throw new Error('indexChunks: documentId required');
  }

  try {
    log('[KnowledgeIndex] Indexing', chunks.length, 'chunks for document:', documentId);
    log('[KnowledgeIndex] NOTE: PASSIVE MODE — Embeddings generated by knowledgeStepRunner');

    // Verify embeddings exist (generated by ingestion pipeline, not here)
    const { count, error: countError } = await supabase
      .from('knowledge_chunks')
      .select('id', { count: 'exact', head: true })
      .eq('document_id', documentId)
      .not('embedding_vector', 'is', null);

    if (countError) {
      warn('[KnowledgeIndex] Failed to verify embeddings:', countError.message);
    } else {
      log('[KnowledgeIndex] Verified embeddings exist:', count, 'chunks');
    }

    // Step 3: Integrity verification (blocking — result feeds is_publishable flag)
    log('[KnowledgeIndex] Starting integrity verification for document:', documentId);
    const integrityResult = await verifyAndPersistIntegrity(documentId);

    if (integrityResult.success) {
      log('[KnowledgeIndex] Integrity score:', integrityResult.report.integrityScore);
      log('[KnowledgeIndex] Publishable:', integrityResult.report.isPublishable);
    } else {
      warn('[KnowledgeIndex] Integrity verification failed:', integrityResult.error);
    }

    // Step 4: Conflict detection (non-blocking — errors must not fail ingestion)
    try {
      const conflictService = getKnowledgeConflictService();
      const conflictResult = await conflictService.detectKnowledgeConflicts(documentId);
      if (conflictResult.conflictsDetected > 0) {
        log('[KnowledgeIndex] Conflicts detected:', {
          documentId,
          count: conflictResult.conflictsDetected,
          timeMs: conflictResult.processingTimeMs,
        });
      }
    } catch (conflictError) {
      warn('[KnowledgeIndex] Conflict detection failed (non-blocking):', conflictError);
    }

    log('[KnowledgeIndex] Indexing complete for document:', documentId);
    return true;
  } catch (err) {
    error('[KnowledgeIndex] Indexing failed:', err);
    return false;
  }
}

// ---------------------------------------------------------------------------
// Cosine similarity helper
// ---------------------------------------------------------------------------

function cosineSimilarity(vecA: number[], vecB: number[]): number {
  if (vecA.length !== vecB.length) {
    throw new Error('Vectors must have same dimensions for cosine similarity');
  }

  let dotProduct = 0;
  let normA = 0;
  let normB = 0;

  for (let i = 0; i < vecA.length; i++) {
    dotProduct += vecA[i] * vecB[i];
    normA += vecA[i] * vecA[i];
    normB += vecB[i] * vecB[i];
  }

  const denominator = Math.sqrt(normA) * Math.sqrt(normB);
  return denominator === 0 ? 0 : dotProduct / denominator;
}

// ---------------------------------------------------------------------------
// Reranking helper
// ---------------------------------------------------------------------------

async function rerankChunks(
  query: string,
  chunks: { chunkId: string; content: string; similarity: number; documentId: string }[]
): Promise<Array<{ chunkId: string; content: string; similarity: number; documentId: string; rerankScore: number }>> {
  try {
    // Generate query embedding once
    const queryEmbedding = await generateEmbedding(query);
    if (!queryEmbedding) {
      throw new Error('Failed to generate query embedding for reranking');
    }

    // Batch embed all chunk contents
    const { embedBatch } = await import('./knowledgeEmbedding.service');
    const texts = chunks.map(c => c.content);
    const embeddings = await embedBatch(texts);

    if (!embeddings || embeddings.length !== chunks.length) {
      throw new Error('[KnowledgeIndex] Reranking batch size mismatch');
    }

    // Calculate rerank scores and sort
    return chunks
      .map((chunk, i) => ({
        ...chunk,
        rerankScore: cosineSimilarity(queryEmbedding, embeddings[i]),
      }))
      .sort((a, b) => b.rerankScore - a.rerankScore);
  } catch (err) {
    error('[KnowledgeIndex] Reranking failed:', err);
    // Return chunks with synthetic rerank scores if reranking fails
    return chunks.map(chunk => ({
      ...chunk,
      rerankScore: chunk.similarity,
    }));
  }
}

// ---------------------------------------------------------------------------
// semanticSearch
// ---------------------------------------------------------------------------

/**
 * Search for the most relevant chunks using hybrid search with reranking.
 * Pure retrieval and ranking layer - performs NO LLM-based processing.
 *
 * Pipeline:
 * 1. Retrieves candidate chunks using hybrid search (pgvector + FTS)
 * 2. Reranks candidates using semantic similarity
 * 3. Returns top limit results
 *
 * Combines pgvector cosine similarity (0.7 weight) with PostgreSQL full-text search (0.3 weight)
 * at retrieval stage, then applies cosine similarity reranking at post-processing stage.
 *
 * Context compression is executed in the generation pipeline (outside retrieval layer).
 *
 * Requires migration 20260307000002_hybrid_rag_search.sql to be applied.
 * Function signature: match_knowledge_chunks(query_embedding vector(1536), query_text text, match_count int)
 */
export async function semanticSearch(
  query: string,
  limit: number = 10
): Promise<{ chunkId: string; content: string; similarity: number; documentId: string }[]> {
  try {
    log('[KnowledgeIndex] Hybrid search for:', query);

    // Retrieve additional candidates for reranking.
    // Using limit * 3 balances recall and embedding cost.
    const retrievalLimit = limit * 3;

    // Generate query embedding for vector similarity (with caching)
    let queryEmbedding = queryEmbeddingCache.get(query);
    if (!queryEmbedding) {
      queryEmbedding = await generateEmbedding(query);
      if (queryEmbedding) {
        queryEmbeddingCache.set(query, queryEmbedding);
      }
    }
    if (!queryEmbedding) {
      throw new Error('Failed to generate query embedding');
    }

    // Hybrid search via pgvector + full-text search
    // Combines vector similarity (0.7) and BM25 FTS (0.3)
    const { data, error: rpcError } = await supabase.rpc('match_knowledge_chunks', {
      query_embedding: queryEmbedding,
      query_text: query,
      match_count: retrievalLimit,
    });

    if (rpcError) {
      throw new Error(`Hybrid search RPC failed: ${rpcError.message}`);
    }

    const retrieved = (data || []).map((row: {
      id: string;
      document_id: string;
      content: string;
      similarity: number;
    }) => ({
      chunkId: row.id,
      documentId: row.document_id,
      content: row.content,
      similarity: row.similarity,
    }));

    log('[KnowledgeIndex] Retrieved', retrieved.length, 'candidates (raw, unranked)');

    // Return raw candidates without reranking.
    // Reranking must happen only once in hybridSearch.service.ts to avoid double-reranking cost.
    return retrieved;
  } catch (err) {
    error('[KnowledgeIndex] Search failed:', err);
    return [];
  }
}

// ---------------------------------------------------------------------------
// getIndexStats
// ---------------------------------------------------------------------------

export async function getIndexStats(): Promise<IndexStats> {
  try {
    const [{ count: totalChunks, error: totalError }, { count: embeddedChunks, error: embeddedError }] =
      await Promise.all([
        supabase.from('knowledge_chunks').select('*', { count: 'exact', head: true }),
        supabase
          .from('knowledge_chunks')
          .select('*', { count: 'exact', head: true })
          .not('embedding_vector', 'is', null),
      ]);

    if (totalError) throw new Error(`Failed to count chunks: ${totalError.message}`);
    if (embeddedError) throw new Error(`Failed to count embeddings: ${embeddedError.message}`);

    const total = totalChunks ?? 0;
    const indexed = embeddedChunks ?? 0;

    return {
      chunksIndexed: indexed,
      embeddingsGenerated: indexed,
      // 1536 dimensions × 4 bytes per float
      indexSize: total * 1536 * 4,
      lastUpdated: new Date().toISOString(),
    };
  } catch (err) {
    error('[KnowledgeIndex] Failed to get stats:', err);
    return {
      chunksIndexed: 0,
      embeddingsGenerated: 0,
      indexSize: 0,
      lastUpdated: new Date().toISOString(),
    };
  }
}

// ---------------------------------------------------------------------------
// backfillEmbeddings
// ---------------------------------------------------------------------------

/**
 * Backfill embeddings for chunks where embedding_vector IS NULL.
 * Called when the ingestion pipeline fails to generate embeddings.
 *
 * @param documentId - Optional: if provided, only backfill for this document
 * @returns Count of embeddings regenerated
 */
export async function backfillEmbeddings(documentId?: string): Promise<number> {
  try {
    log('[KnowledgeIndex] Starting embedding backfill', documentId ? `for document ${documentId}` : 'for all documents');

    // Fetch all chunks with NULL embedding_vector
    let query = supabase
      .from('knowledge_chunks')
      .select('id, document_id, content, chunk_index')
      .is('embedding_vector', null);

    if (documentId) {
      query = query.eq('document_id', documentId);
    }

    const { data: nullChunks, error: fetchError } = await query;

    if (fetchError) {
      throw new Error(`Failed to fetch NULL embedding chunks: ${fetchError.message}`);
    }

    if (!nullChunks || nullChunks.length === 0) {
      log('[KnowledgeIndex] No chunks with NULL embeddings found');
      return 0;
    }

    log('[KnowledgeIndex] Found', nullChunks.length, 'chunks with NULL embeddings');

    // Batch regenerate embeddings with retry logic
    const BATCH_SIZE = 50; // Smaller batches to avoid timeout
    let successCount = 0;

    for (let i = 0; i < nullChunks.length; i += BATCH_SIZE) {
      const batch = nullChunks.slice(i, i + BATCH_SIZE);
      const contents = batch.map((c: any) => c.content);

      try {
        log(`[KnowledgeIndex] Backfilling batch ${Math.floor(i / BATCH_SIZE) + 1}/${Math.ceil(nullChunks.length / BATCH_SIZE)}`);

        // Generate embeddings in batch
        const embeddings = await generateEmbeddingBatch(contents);

        if (!embeddings || embeddings.length !== batch.length) {
          warn(`[KnowledgeIndex] Batch returned ${embeddings?.length ?? 0} embeddings, expected ${batch.length}`);
          continue;
        }

        // Update each chunk with its embedding
        for (let j = 0; j < batch.length; j++) {
          const chunk = batch[j];
          const embedding = embeddings[j];

          if (!embedding || embedding.length === 0) {
            warn(`[KnowledgeIndex] Skipping chunk ${chunk.id} — embedding is invalid`);
            continue;
          }

          const { error: updateError } = await supabase
            .from('knowledge_chunks')
            .update({ embedding_vector: embedding })
            .eq('id', chunk.id);

          if (updateError) {
            warn(`[KnowledgeIndex] Failed to update chunk ${chunk.id}:`, updateError.message);
          } else {
            successCount++;
          }
        }

        log(`[KnowledgeIndex] Batch complete — ${successCount}/${nullChunks.length} total updated`);
      } catch (batchError) {
        warn(`[KnowledgeIndex] Batch failed:`, batchError);
        // Continue with next batch instead of aborting
      }
    }

    log('[KnowledgeIndex] Backfill complete:', successCount, 'embeddings regenerated');
    return successCount;
  } catch (err) {
    error('[KnowledgeIndex] Backfill failed:', err);
    return 0;
  }
}

// Batch embedding helper
// Uses 384 dimensions to match current database schema (vector(384))
// Phase 42 migration will upgrade to 1536, but hasn't been applied yet
async function generateEmbeddingBatch(texts: string[]): Promise<number[][]> {
  const { data, error: fnError } = await supabase.functions.invoke(
    'generate-embedding',
    {
      body: { inputs: texts, model: 'text-embedding-3-small', dimensions: 384 },
    }
  );

  if (fnError) {
    throw new Error(`Edge Function error: ${fnError.message}`);
  }

  if (!data?.embeddings || !Array.isArray(data.embeddings)) {
    throw new Error('Invalid Edge Function response — missing embeddings array');
  }

  return data.embeddings as number[][];
}

// ---------------------------------------------------------------------------
// rebuildIndex
// ---------------------------------------------------------------------------

export async function rebuildIndex(documentId: string): Promise<boolean> {
  try {
    log('[KnowledgeIndex] Rebuilding index for document:', documentId);

    const { data: chunks, error: fetchError } = await supabase
      .from('knowledge_chunks')
      .select('*')
      .eq('document_id', documentId);

    if (fetchError || !chunks) {
      throw new Error(`Failed to fetch chunks: ${fetchError?.message}`);
    }

    const chunkerChunks = chunks.map((chunk: any) => ({
      content: chunk.content,
      tokenCount: chunk.token_count,
      startIndex: 0,
      endIndex: chunk.content.length,
    }));

    return await indexChunks(documentId, chunkerChunks);
  } catch (err) {
    error('[KnowledgeIndex] Rebuild failed:', err);
    return false;
  }
}

// ---------------------------------------------------------------------------
// optimizeIndex
// ---------------------------------------------------------------------------

export async function optimizeIndex(): Promise<{
  duplicatesRemoved: number;
  consolidatedChunks: number;
}> {
  try {
    log('[KnowledgeIndex] Starting index optimization');
    // Deduplication and consolidation logic — reserved for future implementation
    return { duplicatesRemoved: 0, consolidatedChunks: 0 };
  } catch (err) {
    error('[KnowledgeIndex] Optimization failed:', err);
    return { duplicatesRemoved: 0, consolidatedChunks: 0 };
  }
}
