#!/usr/bin/env tsx
/**
 * generateProjectContext.ts — Auto-scan the repository and emit PROJECT_CONTEXT.md
 *
 * Detects:
 *   - Engines (src/core/engines/, src/core/trust/)
 *   - AI services (src/services/ai/)
 *   - RAG services (src/core/rag/)
 *   - Knowledge ingestion (src/core/knowledge/ingestion/, src/services/knowledge/)
 *   - Edge Functions (supabase/functions/)
 *   - Database migrations (supabase/migrations/)
 *   - Infrastructure services
 *   - Workers (rag-worker/)
 *
 * Usage:
 *   pnpm context:generate
 */

import fs   from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT  = path.join(ROOT, 'PROJECT_CONTEXT.md');

// ─── helpers ──────────────────────────────────────────────────────────────────

function exists(p: string): boolean {
  return fs.existsSync(p);
}

function readDir(dir: string): string[] {
  if (!exists(dir)) return [];
  return fs.readdirSync(dir);
}

function walkTs(dir: string): string[] {
  if (!exists(dir)) return [];
  const results: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory() && entry.name !== 'node_modules' && entry.name !== '__tests__') {
      results.push(...walkTs(full));
    } else if (entry.isFile() && /\.(ts|js)$/.test(entry.name) && !entry.name.endsWith('.d.ts') && !entry.name.endsWith('.test.ts') && !entry.name.endsWith('.spec.ts')) {
      results.push(full);
    }
  }
  return results;
}

function rel(p: string): string {
  return path.relative(ROOT, p).replace(/\\/g, '/');
}

function extractExportedName(file: string): string {
  const src = fs.readFileSync(file, 'utf8');
  // First line comment description
  const desc = src.match(/\/\*\*\s*\n\s*\*\s*([^\n]+)/);
  return desc?.[1]?.trim() ?? '';
}

function firstComment(file: string): string {
  try {
    const lines = fs.readFileSync(file, 'utf8').split('\n').slice(0, 5);
    for (const line of lines) {
      const m = line.match(/\/[/*]\s*(.+)/);
      if (m) return m[1].trim().slice(0, 80);
    }
  } catch { /**/ }
  return '';
}

function badge(count: number): string {
  return `\`${count}\``;
}

// ─── scan sections ────────────────────────────────────────────────────────────

// Engines
const engineDir  = path.join(ROOT, 'src/core/engines');
const trustDir   = path.join(ROOT, 'src/core/trust');
const engineFiles = [
  ...walkTs(engineDir).filter(f => f.endsWith('.engine.ts')),
  ...walkTs(trustDir).filter(f => f.endsWith('.engine.ts')),
];

// RAG
const ragDir   = path.join(ROOT, 'src/core/rag');
const ragFiles = walkTs(ragDir).filter(f => f.endsWith('.service.ts') || f.endsWith('.ts'));

// Knowledge ingestion
const kIngDir  = path.join(ROOT, 'src/core/knowledge/ingestion');
const kSvcDir  = path.join(ROOT, 'src/services/knowledge');
const kIngFiles = [...walkTs(kIngDir), ...walkTs(kSvcDir)].filter(f => !f.includes('.bak.'));

// AI services
const aiDir    = path.join(ROOT, 'src/services/ai');
const aiFiles  = walkTs(aiDir).filter(f => f.endsWith('.service.ts') || f.endsWith('.ts')).filter(f => !f.includes('__tests__') && !f.includes('.test.'));

// Infrastructure
const infraDir  = path.join(ROOT, 'src/core/infrastructure');
const infraFiles = walkTs(infraDir).filter(f => f.endsWith('.service.ts'));

// Platform
const platformDir  = path.join(ROOT, 'src/core/platform');
const platformFiles = walkTs(platformDir).filter(f => f.endsWith('.ts'));

// Edge Functions
const funcDir   = path.join(ROOT, 'supabase/functions');
const funcNames = readDir(funcDir).filter(n => !n.startsWith('_') && !n.includes('.'));

// Migrations
const migDir    = path.join(ROOT, 'supabase/migrations');
const migFiles  = readDir(migDir).filter(f => f.endsWith('.sql'));

// Workers
const workerDir   = path.join(ROOT, 'rag-worker');
const workerFiles = walkTs(workerDir).filter(f => !f.includes('node_modules'));

// Scripts
const scriptsDir   = path.join(ROOT, 'scripts');
const scriptFiles  = walkTs(scriptsDir).filter(f => f.endsWith('.ts'));

// ─── build output ─────────────────────────────────────────────────────────────

const now = new Date().toISOString().slice(0, 19).replace('T', ' ') + ' UTC';

const lines: string[] = [];

lines.push(`# PROJECT_CONTEXT.md`);
lines.push(`> Auto-generated by \`pnpm context:generate\` on ${now}`);
lines.push(`> Do not edit manually — re-run the script after structural changes.`);
lines.push('');

// Summary
lines.push(`## Summary`);
lines.push('');
lines.push(`| Category | Count |`);
lines.push(`|----------|-------|`);
lines.push(`| Engines | ${badge(engineFiles.length)} |`);
lines.push(`| AI services | ${badge(aiFiles.filter(f => f.endsWith('.service.ts')).length)} |`);
lines.push(`| RAG services | ${badge(ragFiles.filter(f => f.endsWith('.service.ts')).length)} |`);
lines.push(`| Knowledge ingestion files | ${badge(kIngFiles.length)} |`);
lines.push(`| Infrastructure services | ${badge(infraFiles.length)} |`);
lines.push(`| Platform files | ${badge(platformFiles.length)} |`);
lines.push(`| Edge Functions | ${badge(funcNames.length)} |`);
lines.push(`| Database migrations | ${badge(migFiles.length)} |`);
lines.push(`| Workers | ${badge(workerFiles.length)} |`);
lines.push(`| Dev scripts | ${badge(scriptFiles.length)} |`);
lines.push('');

// Engines
lines.push(`## Engine Pipeline`);
lines.push('');
lines.push(`Execution order managed by \`src/core/platform/engineOrchestrator.ts\`.`);
lines.push('');
lines.push(`| Engine file | Description |`);
lines.push(`|-------------|-------------|`);
for (const f of engineFiles) {
  const name = path.basename(f, '.ts');
  const desc = firstComment(f);
  lines.push(`| \`${rel(f)}\` | ${desc} |`);
}
lines.push('');

// Platform
lines.push(`## Platform Core`);
lines.push('');
lines.push(`| File | Purpose |`);
lines.push(`|------|---------|`);
for (const f of platformFiles) {
  lines.push(`| \`${rel(f)}\` | ${firstComment(f)} |`);
}
lines.push('');

// RAG
lines.push(`## RAG System`);
lines.push('');
lines.push(`| File | Purpose |`);
lines.push(`|------|---------|`);
for (const f of ragFiles.filter(f => f.endsWith('.service.ts'))) {
  lines.push(`| \`${rel(f)}\` | ${firstComment(f)} |`);
}
lines.push('');

// Knowledge ingestion
lines.push(`## Knowledge Ingestion Pipeline`);
lines.push('');
lines.push(`> Critical: all writes to \`knowledge_chunks\` must use column \`embedding_vector\`, never \`embedding\`.`);
lines.push('');
lines.push(`| File | Purpose |`);
lines.push(`|------|---------|`);
for (const f of kIngFiles) {
  lines.push(`| \`${rel(f)}\` | ${firstComment(f)} |`);
}
lines.push('');

// AI Services
lines.push(`## AI Services`);
lines.push('');
lines.push(`| File | Purpose |`);
lines.push(`|------|---------|`);
for (const f of aiFiles.filter(f => f.endsWith('.service.ts'))) {
  lines.push(`| \`${rel(f)}\` | ${firstComment(f)} |`);
}
lines.push('');

// Infrastructure
lines.push(`## Infrastructure`);
lines.push('');
lines.push(`| File | Purpose |`);
lines.push(`|------|---------|`);
for (const f of infraFiles) {
  lines.push(`| \`${rel(f)}\` | ${firstComment(f)} |`);
}
lines.push('');

// Workers
lines.push(`## Workers`);
lines.push('');
lines.push(`| File | Description |`);
lines.push(`|------|-------------|`);
for (const f of workerFiles) {
  lines.push(`| \`${rel(f)}\` | ${firstComment(f)} |`);
}
lines.push('');

// Edge Functions
lines.push(`## Edge Functions (Deno)`);
lines.push('');
lines.push(`Deploy: \`supabase functions deploy <name>\``);
lines.push('');
lines.push(`| Function | Entry point |`);
lines.push(`|----------|-------------|`);
for (const name of funcNames) {
  const entry = path.join(funcDir, name, 'index.ts');
  const entryJs = path.join(funcDir, name, 'index.js');
  const hasEntry = exists(entry) ? `supabase/functions/${name}/index.ts` : exists(entryJs) ? `supabase/functions/${name}/index.js` : `supabase/functions/${name}/`;
  lines.push(`| \`${name}\` | \`${hasEntry}\` |`);
}
lines.push('');

// Migrations
lines.push(`## Database Migrations (${migFiles.length} total)`);
lines.push('');
lines.push(`Applied via Supabase dashboard. \`supabase migration list\` does not track them (all show as untracked).`);
lines.push('');
lines.push(`Most recent migrations:`);
lines.push('');
const recentMigs = migFiles.slice(-15);
for (const m of recentMigs) {
  lines.push(`- \`supabase/migrations/${m}\``);
}
lines.push('');

// Dev scripts
lines.push(`## Dev Scripts`);
lines.push('');
lines.push(`| Script | Command | Purpose |`);
lines.push(`|--------|---------|---------|`);
for (const f of scriptFiles) {
  const name = path.basename(f, '.ts');
  const desc = firstComment(f);
  lines.push(`| \`${name}\` | \`npx tsx scripts/${name}.ts\` | ${desc} |`);
}
lines.push('');

// Architecture notes
lines.push(`## Architectural Notes`);
lines.push('');
lines.push(`- **Column constraint**: \`knowledge_chunks.embedding_vector\` is \`VECTOR(384)\`. Never write to \`embedding\`.`);
lines.push(`- **rag-worker is standalone**: \`rag-worker/worker.js\` is a pure Node.js script with its own Supabase client. Changes in \`src/\` do not affect it.`);
lines.push(`- **Engine order is strict**: The engine orchestrator runs engines in a fixed sequence. Do not reorder.`);
lines.push(`- **RLS is active**: Use \`SUPABASE_SERVICE_ROLE_KEY\` for all server-side writes to knowledge tables.`);
lines.push(`- **Ingestion trigger**: \`on_document_pending\` fires automatically on INSERT. Never manually set status to \`processing\`.`);

// Write file
fs.writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(`✓ PROJECT_CONTEXT.md written (${lines.length} lines)`);
console.log(`  Detected: ${engineFiles.length} engines · ${funcNames.length} edge functions · ${migFiles.length} migrations · ${workerFiles.length} worker files`);
