/**
 * Page de détail d'un appel d'offres (MOA)
 * Affiche les détails, DCE, et permet de gérer les réponses
 */

import React, { useEffect, useState, useCallback } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Separator } from '@/components/ui/separator';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  ArrowLeft, Edit, FileText, Download, Send, Eye, Users, Euro,
  Calendar, Clock, AlertTriangle, Loader2, CheckCircle2, MapPin,
  Briefcase, FileSpreadsheet, Building, Phone, Mail, ExternalLink,
  Copy, Share2, XCircle, ArrowRight
} from 'lucide-react';
import { TenderService } from '@/services/tender/tender.service';
import { supabase } from '@/lib/supabase';
import type {
  Tender,
  TenderDocument,
  TenderInvitation,
  TenderStatus,
} from '@/types/tender';
import { useToast } from '@/hooks/use-toast';

const STATUS_CONFIG: Record<TenderStatus, { label: string; color: string }> = {
  draft: { label: 'Brouillon', color: 'bg-gray-500' },
  ready: { label: 'Prêt à publier', color: 'bg-yellow-500' },
  published: { label: 'Publié', color: 'bg-green-500' },
  closed: { label: 'Fermé', color: 'bg-blue-500' },
  evaluation: { label: 'En évaluation', color: 'bg-purple-500' },
  attributed: { label: 'Attribué', color: 'bg-primary' },
  cancelled: { label: 'Annulé', color: 'bg-red-500' },
  archived: { label: 'Archivé', color: 'bg-gray-400' },
};

export function TenderDetailPage() {
  const { tenderId } = useParams<{ tenderId: string }>();
  const navigate = useNavigate();
  const { toast } = useToast();

  const [tender, setTender] = useState<Tender | null>(null);
  const [documents, setDocuments] = useState<TenderDocument[]>([]);
  const [invitations, setInvitations] = useState<TenderInvitation[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isPublishing, setIsPublishing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // État du dialogue de publication
  const [showPublishDialog, setShowPublishDialog] = useState(false);
  const [publishSettings, setPublishSettings] = useState({
    responseDeadline: '',
    questionsDeadline: '',
    visibility: 'private' as 'private' | 'restricted' | 'public',
  });

  // Charger les données
  useEffect(() => {
    const loadTender = async () => {
      if (!tenderId) return;

      setIsLoading(true);
      setError(null);

      try {
        const tenderData = await TenderService.getById(tenderId);
        if (!tenderData) {
          setError('Appel d\'offres non trouvé');
          return;
        }

        setTender(tenderData);
        setDocuments(tenderData.dceDocuments || []);

        // Charger les invitations
        const invitationsData = await TenderService.getInvitations(tenderId);
        setInvitations(invitationsData);

        // Charger les documents depuis la table tender_documents
        const { data: docsData } = await supabase
          .from('tender_documents')
          .select('*')
          .eq('tender_id', tenderId)
          .order('document_type');

        if (docsData) {
          setDocuments(docsData.map(d => ({
            id: d.id,
            tenderId: d.tender_id,
            documentType: d.document_type,
            name: d.name,
            description: d.description,
            version: d.version,
            generatedContent: d.generated_content,
            isAutoGenerated: d.is_auto_generated,
            isRequired: d.is_required,
            isPublic: d.is_public,
            createdAt: new Date(d.created_at),
            updatedAt: new Date(d.updated_at),
          })));
        }
      } catch (err) {
        console.error('Erreur chargement AO:', err);
        setError('Impossible de charger l\'appel d\'offres');
      } finally {
        setIsLoading(false);
      }
    };

    loadTender();
  }, [tenderId]);

  // Publier l'AO
  const handlePublish = useCallback(async () => {
    if (!tender || !publishSettings.responseDeadline) return;

    setIsPublishing(true);
    try {
      const updatedTender = await TenderService.publish({
        tenderId: tender.id,
        responseDeadline: new Date(publishSettings.responseDeadline),
        questionsDeadline: publishSettings.questionsDeadline
          ? new Date(publishSettings.questionsDeadline)
          : undefined,
      });

      setTender(updatedTender);
      setShowPublishDialog(false);

      toast({
        title: 'Appel d\'offres publié',
        description: 'Les entreprises peuvent maintenant consulter et répondre à votre AO',
      });
    } catch (err) {
      console.error('Erreur publication:', err);
      toast({
        title: 'Erreur',
        description: 'Impossible de publier l\'appel d\'offres',
        variant: 'destructive',
      });
    } finally {
      setIsPublishing(false);
    }
  }, [tender, publishSettings, toast]);

  // Fermer l'AO
  const handleClose = useCallback(async () => {
    if (!tender) return;

    try {
      const updatedTender = await TenderService.close(tender.id);
      setTender(updatedTender);

      toast({
        title: 'Appel d\'offres fermé',
        description: 'Les entreprises ne peuvent plus soumettre de réponses',
      });
    } catch (err) {
      toast({
        title: 'Erreur',
        description: 'Impossible de fermer l\'appel d\'offres',
        variant: 'destructive',
      });
    }
  }, [tender, toast]);

  // Copier le lien de partage
  const copyShareLink = useCallback(() => {
    const link = `${window.location.origin}/ao/${tender?.id}`;
    navigator.clipboard.writeText(link);
    toast({
      title: 'Lien copié',
      description: 'Le lien a été copié dans le presse-papiers',
    });
  }, [tender, toast]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error || !tender) {
    return (
      <div className="container max-w-4xl mx-auto px-4 py-8">
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription>{error || 'Appel d\'offres non trouvé'}</AlertDescription>
        </Alert>
        <Button variant="outline" className="mt-4" onClick={() => navigate('/tenders')}>
          <ArrowLeft className="w-4 h-4 mr-2" />
          Retour aux AO
        </Button>
      </div>
    );
  }

  const statusConfig = STATUS_CONFIG[tender.status];
  const isEditable = tender.status === 'draft' || tender.status === 'ready';
  const canPublish = tender.status === 'ready' && documents.length > 0;
  const canClose = tender.status === 'published';

  return (
    <div className="min-h-screen bg-muted/20">
      <div className="container max-w-6xl mx-auto px-4 py-8">
        {/* Navigation */}
        <div className="flex items-center justify-between mb-6">
          <Button variant="ghost" asChild>
            <Link to="/tenders">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Mes appels d'offres
            </Link>
          </Button>
          <div className="flex items-center gap-2">
            {isEditable && (
              <Button variant="outline">
                <Edit className="w-4 h-4 mr-2" />
                Modifier
              </Button>
            )}
            <Button variant="outline" onClick={copyShareLink}>
              <Copy className="w-4 h-4 mr-2" />
              Copier le lien
            </Button>
            {canPublish && (
              <Dialog open={showPublishDialog} onOpenChange={setShowPublishDialog}>
                <DialogTrigger asChild>
                  <Button>
                    <Send className="w-4 h-4 mr-2" />
                    Publier
                  </Button>
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>Publier l'appel d'offres</DialogTitle>
                    <DialogDescription>
                      Configurez les dates limites et la visibilité de votre consultation
                    </DialogDescription>
                  </DialogHeader>
                  <div className="space-y-4 py-4">
                    <div className="space-y-2">
                      <Label htmlFor="responseDeadline">Date limite de réponse *</Label>
                      <Input
                        id="responseDeadline"
                        type="datetime-local"
                        value={publishSettings.responseDeadline}
                        onChange={(e) => setPublishSettings(prev => ({
                          ...prev,
                          responseDeadline: e.target.value,
                        }))}
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="questionsDeadline">Date limite des questions</Label>
                      <Input
                        id="questionsDeadline"
                        type="datetime-local"
                        value={publishSettings.questionsDeadline}
                        onChange={(e) => setPublishSettings(prev => ({
                          ...prev,
                          questionsDeadline: e.target.value,
                        }))}
                      />
                    </div>
                    <div className="space-y-2">
                      <Label>Visibilité</Label>
                      <Select
                        value={publishSettings.visibility}
                        onValueChange={(v) => setPublishSettings(prev => ({
                          ...prev,
                          visibility: v as typeof prev.visibility,
                        }))}
                      >
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="private">Privé (invitation uniquement)</SelectItem>
                          <SelectItem value="restricted">Restreint (entreprises sélectionnées)</SelectItem>
                          <SelectItem value="public">Public (toutes les entreprises)</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <DialogFooter>
                    <Button variant="outline" onClick={() => setShowPublishDialog(false)}>
                      Annuler
                    </Button>
                    <Button
                      onClick={handlePublish}
                      disabled={isPublishing || !publishSettings.responseDeadline}
                    >
                      {isPublishing ? (
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      ) : (
                        <Send className="w-4 h-4 mr-2" />
                      )}
                      Publier
                    </Button>
                  </DialogFooter>
                </DialogContent>
              </Dialog>
            )}
            {canClose && (
              <Button variant="destructive" onClick={handleClose}>
                <XCircle className="w-4 h-4 mr-2" />
                Fermer aux réponses
              </Button>
            )}
          </div>
        </div>

        {/* En-tête */}
        <Card className="mb-6">
          <CardHeader>
            <div className="flex items-start justify-between">
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <Badge variant="outline" className="font-mono">
                    {tender.reference}
                  </Badge>
                  <Badge className={statusConfig.color}>
                    {statusConfig.label}
                  </Badge>
                  <Badge variant="outline">
                    {tender.visibility === 'private' ? 'Privé' :
                     tender.visibility === 'restricted' ? 'Restreint' : 'Public'}
                  </Badge>
                </div>
                <CardTitle className="text-2xl">{tender.title}</CardTitle>
                {tender.description && (
                  <CardDescription className="mt-2">
                    {tender.description}
                  </CardDescription>
                )}
              </div>
              <div className="text-right">
                <div className="text-sm text-muted-foreground">Créé le</div>
                <div className="font-medium">
                  {tender.createdAt.toLocaleDateString('fr-FR')}
                </div>
              </div>
            </div>
          </CardHeader>
        </Card>

        {/* Contenu */}
        <Tabs defaultValue="overview">
          <TabsList className="mb-6">
            <TabsTrigger value="overview">Vue d'ensemble</TabsTrigger>
            <TabsTrigger value="documents">Documents ({documents.length})</TabsTrigger>
            <TabsTrigger value="responses">
              Réponses ({tender.responsesCount})
            </TabsTrigger>
            <TabsTrigger value="invitations">
              Invitations ({invitations.length})
            </TabsTrigger>
          </TabsList>

          {/* Vue d'ensemble */}
          <TabsContent value="overview" className="space-y-6">
            {/* Statistiques */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <Card>
                <CardContent className="pt-6">
                  <div className="text-sm text-muted-foreground mb-1">Lots</div>
                  <div className="text-2xl font-bold">{tender.lotsCount}</div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="pt-6">
                  <div className="text-sm text-muted-foreground mb-1">Vues</div>
                  <div className="text-2xl font-bold">{tender.viewsCount}</div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="pt-6">
                  <div className="text-sm text-muted-foreground mb-1">Téléchargements</div>
                  <div className="text-2xl font-bold">{tender.downloadsCount}</div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="pt-6">
                  <div className="text-sm text-muted-foreground mb-1">Réponses</div>
                  <div className="text-2xl font-bold text-primary">{tender.responsesCount}</div>
                </CardContent>
              </Card>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Informations projet */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <Briefcase className="w-5 h-5 text-primary" />
                    Informations projet
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3 text-sm">
                  {tender.workAddress && (
                    <div className="flex items-start gap-2">
                      <MapPin className="w-4 h-4 text-muted-foreground mt-0.5" />
                      <div>
                        <div>{tender.workAddress.street}</div>
                        <div className="text-muted-foreground">
                          {tender.workPostalCode} {tender.workCity}
                        </div>
                      </div>
                    </div>
                  )}
                  {(tender.estimatedBudgetMin || tender.estimatedBudgetMax) && (
                    <div className="flex items-center gap-2">
                      <Euro className="w-4 h-4 text-muted-foreground" />
                      <span>
                        Budget: {tender.estimatedBudgetMin?.toLocaleString('fr-FR')} € - {tender.estimatedBudgetMax?.toLocaleString('fr-FR')} €
                      </span>
                    </div>
                  )}
                  {tender.estimatedDurationDays && (
                    <div className="flex items-center gap-2">
                      <Clock className="w-4 h-4 text-muted-foreground" />
                      <span>Durée estimée: {Math.ceil(tender.estimatedDurationDays / 7)} semaines</span>
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Dates et délais */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <Calendar className="w-5 h-5 text-primary" />
                    Dates clés
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3 text-sm">
                  {tender.publishedAt && (
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Publication</span>
                      <span>{tender.publishedAt.toLocaleDateString('fr-FR')}</span>
                    </div>
                  )}
                  {tender.questionsDeadline && (
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Limite questions</span>
                      <span>{tender.questionsDeadline.toLocaleDateString('fr-FR')}</span>
                    </div>
                  )}
                  {tender.responseDeadline && (
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Limite réponses</span>
                      <span className="font-medium">
                        {tender.responseDeadline.toLocaleDateString('fr-FR')}
                      </span>
                    </div>
                  )}
                  {tender.desiredStartDate && (
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Démarrage souhaité</span>
                      <span>{tender.desiredStartDate.toLocaleDateString('fr-FR')}</span>
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Contact */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <Users className="w-5 h-5 text-primary" />
                    Contact MOA
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3 text-sm">
                  {tender.contactName && (
                    <div>{tender.contactName}</div>
                  )}
                  {tender.contactEmail && (
                    <div className="flex items-center gap-2">
                      <Mail className="w-4 h-4 text-muted-foreground" />
                      <a href={`mailto:${tender.contactEmail}`} className="text-primary hover:underline">
                        {tender.contactEmail}
                      </a>
                    </div>
                  )}
                  {tender.contactPhone && (
                    <div className="flex items-center gap-2">
                      <Phone className="w-4 h-4 text-muted-foreground" />
                      <a href={`tel:${tender.contactPhone}`} className="text-primary hover:underline">
                        {tender.contactPhone}
                      </a>
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Critères d'évaluation */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <CheckCircle2 className="w-5 h-5 text-primary" />
                    Critères d'évaluation
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    {tender.evaluationCriteria.map((criterion, i) => (
                      <div key={i} className="flex items-center justify-between">
                        <span className="text-sm capitalize">{criterion.name}</span>
                        <Badge variant="outline">{criterion.weight}%</Badge>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Lots */}
            {tender.selectedLots && tender.selectedLots.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg">Lots de travaux</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {tender.selectedLots.map((lot) => (
                      <div
                        key={lot.lotNumber}
                        className="flex items-center justify-between p-3 border rounded-lg"
                      >
                        <div className="flex items-center gap-3">
                          <Badge variant="outline" className="font-mono">
                            Lot {lot.lotNumber}
                          </Badge>
                          <div>
                            <div className="font-medium">{lot.lotName}</div>
                            {lot.description && (
                              <div className="text-sm text-muted-foreground">
                                {lot.description}
                              </div>
                            )}
                          </div>
                        </div>
                        <div className="text-right text-sm">
                          {lot.rgeRequired && (
                            <Badge variant="secondary" className="mr-2">RGE requis</Badge>
                          )}
                          {(lot.estimatedPriceMin || lot.estimatedPriceMax) && (
                            <span className="text-muted-foreground">
                              {lot.estimatedPriceMin?.toLocaleString('fr-FR')} € - {lot.estimatedPriceMax?.toLocaleString('fr-FR')} €
                            </span>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}
          </TabsContent>

          {/* Documents DCE */}
          <TabsContent value="documents" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileSpreadsheet className="w-5 h-5" />
                  Dossier de Consultation des Entreprises (DCE)
                </CardTitle>
                <CardDescription>
                  Documents générés automatiquement pour la consultation
                </CardDescription>
              </CardHeader>
              <CardContent>
                {documents.length > 0 ? (
                  <div className="space-y-3">
                    {documents.map((doc) => (
                      <div
                        key={doc.id}
                        className="flex items-center justify-between p-4 border rounded-lg hover:bg-muted/50"
                      >
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                            <FileText className="w-5 h-5 text-primary" />
                          </div>
                          <div>
                            <div className="font-medium">{doc.name}</div>
                            <div className="text-sm text-muted-foreground">
                              {doc.documentType.toUpperCase()} • Version {doc.version}
                              {doc.description && ` • ${doc.description}`}
                            </div>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          <Badge variant="outline">
                            {doc.isAutoGenerated ? 'Auto-généré' : 'Manuel'}
                          </Badge>
                          <Button variant="ghost" size="icon">
                            <Eye className="w-4 h-4" />
                          </Button>
                          <Button variant="ghost" size="icon">
                            <Download className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-8 text-muted-foreground">
                    <FileText className="w-12 h-12 mx-auto mb-2 opacity-50" />
                    <p>Aucun document généré</p>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          {/* Réponses */}
          <TabsContent value="responses" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Réponses reçues</CardTitle>
                <CardDescription>
                  {tender.responsesCount} entreprise(s) ont répondu à votre consultation
                </CardDescription>
              </CardHeader>
              <CardContent>
                {tender.responsesCount > 0 ? (
                  <div className="text-center py-8">
                    <Button onClick={() => navigate(`/tenders/${tender.id}/responses`)}>
                      <Eye className="w-4 h-4 mr-2" />
                      Voir les réponses
                      <ArrowRight className="w-4 h-4 ml-2" />
                    </Button>
                  </div>
                ) : (
                  <div className="text-center py-12 text-muted-foreground">
                    <Users className="w-12 h-12 mx-auto mb-4 opacity-50" />
                    <p>Aucune réponse reçue pour le moment</p>
                    {tender.status === 'published' && (
                      <p className="text-sm mt-2">
                        Les entreprises peuvent répondre jusqu'au{' '}
                        {tender.responseDeadline?.toLocaleDateString('fr-FR')}
                      </p>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          {/* Invitations */}
          <TabsContent value="invitations" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Entreprises invitées</CardTitle>
                <CardDescription>
                  Gérez les entreprises invitées à répondre
                </CardDescription>
              </CardHeader>
              <CardContent>
                {invitations.length > 0 ? (
                  <div className="space-y-3">
                    {invitations.map((inv) => (
                      <div
                        key={inv.id}
                        className="flex items-center justify-between p-4 border rounded-lg"
                      >
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                            <Building className="w-5 h-5 text-primary" />
                          </div>
                          <div>
                            <div className="font-medium">{inv.companyName}</div>
                            <div className="text-sm text-muted-foreground">
                              {inv.companyEmail}
                            </div>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          <Badge variant={
                            inv.status === 'responded' ? 'default' :
                            inv.status === 'viewed' || inv.status === 'downloaded' ? 'secondary' :
                            inv.status === 'declined' ? 'destructive' : 'outline'
                          }>
                            {inv.status === 'pending' && 'En attente'}
                            {inv.status === 'sent' && 'Envoyée'}
                            {inv.status === 'viewed' && 'Vue'}
                            {inv.status === 'downloaded' && 'Téléchargée'}
                            {inv.status === 'responded' && 'Répondu'}
                            {inv.status === 'declined' && 'Décliné'}
                          </Badge>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-12 text-muted-foreground">
                    <Users className="w-12 h-12 mx-auto mb-4 opacity-50" />
                    <p>Aucune invitation envoyée</p>
                    <p className="text-sm mt-2">
                      Vous pouvez inviter des entreprises spécifiques à répondre à votre AO
                    </p>
                    <Button variant="outline" className="mt-4">
                      <Send className="w-4 h-4 mr-2" />
                      Inviter des entreprises
                    </Button>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}

export default TenderDetailPage;
