-- ============================================================================
-- MIGRATION: Knowledge Conflict Detection - Data Table
-- PURPOSE: Store detected conflicts between knowledge documents
-- PHASE: Conflict Detection MVP
-- ============================================================================
-- This migration creates a table to store conflict detection results.
-- Conflicts are detected by comparing embeddings across documents.
-- This table is read/write but conflict detection is non-blocking.

-- ============================================================================
-- 1️⃣ CREATE TABLE: knowledge_conflicts
-- ============================================================================
-- Stores detected conflicts between document chunks
-- Used by: KnowledgeConflictService for conflict detection and tracking

CREATE TABLE IF NOT EXISTS knowledge_conflicts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Document references
  document_a_id UUID NOT NULL,
  document_b_id UUID NOT NULL,

  -- Chunk references (optional, for granularity)
  chunk_a_id UUID,
  chunk_b_id UUID,

  -- Similarity metrics
  similarity_score NUMERIC(3, 2) NOT NULL CHECK (similarity_score >= 0 AND similarity_score <= 1),
  conflict_score NUMERIC(3, 2) NOT NULL CHECK (conflict_score >= 0 AND conflict_score <= 1),

  -- Conflict classification
  conflict_type TEXT NOT NULL CHECK (conflict_type IN (
    'numerical_conflict',
    'regulatory_conflict',
    'semantic_contradiction',
    'source_priority_conflict'
  )),

  -- Conflict description
  conflict_reason TEXT,

  -- Metadata
  detected_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  status TEXT DEFAULT 'unreviewed' CHECK (status IN ('unreviewed', 'reviewed', 'resolved', 'ignored')),
  reviewed_at TIMESTAMP WITH TIME ZONE,
  reviewed_by UUID REFERENCES profiles(id) ON DELETE SET NULL,

  -- Constraints
  CONSTRAINT different_documents CHECK (document_a_id != document_b_id),
  CONSTRAINT valid_chunk_refs CHECK (
    (chunk_a_id IS NULL AND chunk_b_id IS NULL) OR
    (chunk_a_id IS NOT NULL AND chunk_b_id IS NOT NULL)
  )
);

COMMENT ON TABLE knowledge_conflicts IS
'Detected conflicts between knowledge documents based on embedding similarity.
Conflicts are non-blocking and stored for review by admins.
Generated by KnowledgeConflictService after document ingestion.';

-- ============================================================================
-- 2️⃣ CREATE INDEXES
-- ============================================================================
-- Optimize queries for conflict detection and review

CREATE INDEX IF NOT EXISTS idx_knowledge_conflicts_doc_a
ON knowledge_conflicts(document_a_id);

CREATE INDEX IF NOT EXISTS idx_knowledge_conflicts_doc_b
ON knowledge_conflicts(document_b_id);

CREATE INDEX IF NOT EXISTS idx_knowledge_conflicts_status
ON knowledge_conflicts(status)
WHERE status = 'unreviewed';

CREATE INDEX IF NOT EXISTS idx_knowledge_conflicts_score
ON knowledge_conflicts(conflict_score DESC)
WHERE status = 'unreviewed';

CREATE INDEX IF NOT EXISTS idx_knowledge_conflicts_type
ON knowledge_conflicts(conflict_type);

CREATE INDEX IF NOT EXISTS idx_knowledge_conflicts_detected_at
ON knowledge_conflicts(detected_at DESC);

COMMENT ON INDEX idx_knowledge_conflicts_status IS
'Fast lookup of unreviewed conflicts for admin dashboards.';

COMMENT ON INDEX idx_knowledge_conflicts_score IS
'Sort conflicts by severity (highest first) for prioritized review.';

-- ============================================================================
-- 3️⃣ CREATE UNIQUE CONSTRAINT
-- ============================================================================
-- Prevent duplicate conflict entries for same document pair

ALTER TABLE knowledge_conflicts
ADD CONSTRAINT unique_document_pair_conflict
UNIQUE (
  LEAST(document_a_id, document_b_id),
  GREATEST(document_a_id, document_b_id),
  conflict_type
);

COMMENT ON CONSTRAINT unique_document_pair_conflict IS
'Prevent duplicate conflicts for the same document pair and type.';

-- ============================================================================
-- 4️⃣ VIEW: unreviewed_conflicts
-- ============================================================================
-- Quick view of all unreviewed conflicts for admin dashboards

CREATE OR REPLACE VIEW unreviewed_conflicts AS
SELECT
  kc.id,
  kc.document_a_id,
  kc.document_b_id,
  kc.similarity_score,
  kc.conflict_score,
  kc.conflict_type,
  kc.conflict_reason,
  kc.detected_at,
  da.title as document_a_title,
  da.category as document_a_category,
  db.title as document_b_title,
  db.category as document_b_category
FROM knowledge_conflicts kc
INNER JOIN knowledge_documents da ON kc.document_a_id = da.id
INNER JOIN knowledge_documents db ON kc.document_b_id = db.id
WHERE kc.status = 'unreviewed'
ORDER BY kc.conflict_score DESC;

COMMENT ON VIEW unreviewed_conflicts IS
'All unreviewed conflicts sorted by severity for admin review.';

-- ============================================================================
-- 5️⃣ RLS POLICIES
-- ============================================================================
-- Read access for authenticated users (metrics only)
-- Write access for system processes only

ALTER TABLE knowledge_conflicts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "conflicts_read_authenticated" ON knowledge_conflicts;
CREATE POLICY "conflicts_read_authenticated" ON knowledge_conflicts
  FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "conflicts_write_system" ON knowledge_conflicts;
CREATE POLICY "conflicts_write_system" ON knowledge_conflicts
  FOR INSERT WITH CHECK (TRUE);

DROP POLICY IF EXISTS "conflicts_update_admin" ON knowledge_conflicts;
CREATE POLICY "conflicts_update_admin" ON knowledge_conflicts
  FOR UPDATE USING (
    auth.role() = 'authenticated' AND
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND user_type = 'admin')
  );

-- ============================================================================
-- MIGRATION NOTES
-- ============================================================================
--
-- WHAT WAS ADDED:
-- ✅ knowledge_conflicts table
-- ✅ Indexes for efficient queries
-- ✅ Unique constraint to prevent duplicates
-- ✅ unreviewed_conflicts view
-- ✅ RLS policies
--
-- WHAT WAS NOT MODIFIED:
-- ✓ knowledge_documents (untouched)
-- ✓ knowledge_chunks (untouched)
-- ✓ knowledge_embeddings (untouched)
-- ✓ Any ingestion tables
-- ✓ Any RAG tables
--
-- BACKWARD COMPATIBILITY:
-- ✓ 100% backward compatible (new table only)
-- ✓ Existing code continues working unchanged
-- ✓ No performance impact on ingestion
--
-- CONFLICT DETECTION FLOW:
-- 1. Document is ingested normally
-- 2. After embeddings are created and verified
-- 3. KnowledgeConflictService detects conflicts
-- 4. Conflicts are stored in this table (non-blocking)
-- 5. Admin reviews conflicts at their leisure
