-- Create LLM Usage Log Table
-- Tracks all LLM API calls for cost analysis and monitoring

CREATE TABLE IF NOT EXISTS llm_usage_log (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT,
  action TEXT NOT NULL,
  model TEXT NOT NULL,
  input_tokens INTEGER NOT NULL,
  output_tokens INTEGER NOT NULL,
  total_tokens INTEGER NOT NULL,
  latency_ms INTEGER NOT NULL,
  cost_estimate DECIMAL(10, 8) NOT NULL,
  cost_currency TEXT DEFAULT 'USD',
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  session_id TEXT,
  error BOOLEAN DEFAULT FALSE,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- Indexes for common queries
  INDEX idx_user_id (user_id),
  INDEX idx_action (action),
  INDEX idx_model (model),
  INDEX idx_timestamp (timestamp),
  INDEX idx_session_id (session_id)
);

-- Create view for daily cost summary
CREATE OR REPLACE VIEW daily_llm_costs AS
SELECT
  DATE(timestamp) as date,
  COUNT(*) as total_requests,
  SUM(total_tokens) as total_tokens,
  SUM(input_tokens) as input_tokens,
  SUM(output_tokens) as output_tokens,
  SUM(cost_estimate) as total_cost,
  AVG(latency_ms) as avg_latency_ms,
  MAX(cost_estimate) as max_request_cost,
  MIN(cost_estimate) as min_request_cost
FROM llm_usage_log
WHERE NOT error
GROUP BY DATE(timestamp)
ORDER BY date DESC;

-- Create view for model cost summary
CREATE OR REPLACE VIEW model_llm_costs AS
SELECT
  model,
  COUNT(*) as total_requests,
  SUM(total_tokens) as total_tokens,
  SUM(input_tokens) as input_tokens,
  SUM(output_tokens) as output_tokens,
  SUM(cost_estimate) as total_cost,
  AVG(latency_ms) as avg_latency_ms,
  AVG(cost_estimate) as avg_cost_per_request
FROM llm_usage_log
WHERE NOT error
GROUP BY model
ORDER BY total_cost DESC;

-- Create view for action cost summary
CREATE OR REPLACE VIEW action_llm_costs AS
SELECT
  action,
  COUNT(*) as total_requests,
  SUM(total_tokens) as total_tokens,
  SUM(input_tokens) as input_tokens,
  SUM(output_tokens) as output_tokens,
  SUM(cost_estimate) as total_cost,
  AVG(latency_ms) as avg_latency_ms,
  AVG(cost_estimate) as avg_cost_per_request
FROM llm_usage_log
WHERE NOT error
GROUP BY action
ORDER BY total_cost DESC;

-- Create view for user usage summary
CREATE OR REPLACE VIEW user_llm_usage AS
SELECT
  user_id,
  COUNT(*) as total_requests,
  SUM(total_tokens) as total_tokens,
  SUM(cost_estimate) as total_cost,
  MIN(timestamp) as first_usage,
  MAX(timestamp) as last_usage
FROM llm_usage_log
WHERE NOT error AND user_id IS NOT NULL
GROUP BY user_id
ORDER BY total_cost DESC;

-- Add comment to table
COMMENT ON TABLE llm_usage_log IS
'Tracks all LLM API calls for cost analysis, monitoring, and billing purposes';

COMMENT ON COLUMN llm_usage_log.input_tokens IS
'Number of tokens used in the API request (actual from API response)';

COMMENT ON COLUMN llm_usage_log.output_tokens IS
'Number of tokens generated by the LLM (actual from API response)';

COMMENT ON COLUMN llm_usage_log.cost_estimate IS
'Estimated cost in USD based on current pricing';

COMMENT ON COLUMN llm_usage_log.latency_ms IS
'Time in milliseconds from request to response';

COMMENT ON COLUMN llm_usage_log.error IS
'Whether this request resulted in an error';
